#!/usr/bin/env bash

### Helpers begin
check_deps() {
    local missing
    for d in "${deps[@]}"; do
        if [[ -z $(command -v "$d") ]]; then
            # Force absolute path
            if [[ ! -f "/$d" ]]; then
                err "$d was not found"
                missing="true"
            fi
        fi
    done; unset d
    [[ -z $missing ]] || exit 128
}
err() { echo -e "${color:+\e[31m}[!] $*\e[0m"; }
errx() { err "${*:2}"; exit "$1"; }
good() { echo -e "${color:+\e[32m}[+] $*\e[0m"; }
info() { echo -e "${color:+\e[37m}[*] $*\e[0m"; }
long_opt() {
    local arg shift="0"
    case "$1" in
        "--"*"="*) arg="${1#*=}"; [[ -n $arg ]] || usage 127 ;;
        *) shift="1"; shift; [[ $# -gt 0 ]] || usage 127; arg="$1" ;;
    esac
    echo "$arg"
    return $shift
}
subinfo() { echo -e "${color:+\e[36m}[=] $*\e[0m"; }
warn() { echo -e "${color:+\e[33m}[-] $*\e[0m"; }
### Helpers end

usage() {
    cat <<EOF
Usage: ${0##*/} [OPTIONS]

Launch the community edition of BurpSuite.

Options:
    -c, --clear    Clear cache and download the newest BurpSuite
    -h             Display this help message
    --help         Pass-thru to the BurpSuite jar
    --no-color     Disable colorized output

EOF
    exit "$1"
}

declare -a args deps
unset clear help
color="true"
deps+=("curl")
deps+=("java")

# Check for missing dependencies
check_deps

# Parse command line options
while [[ $# -gt 0 ]]; do
    case "$1" in
        "--") shift && args+=("$@") && break ;;
        "-c"|"--clear-cache") clear="true" ;;
        "-h") help="true" ;;
        "--no-color") unset color ;;
        *) args+=("$1") ;;
    esac
    shift
done
[[ ${#args[@]} -eq 0 ]] || set -- "${args[@]}"

# Check for valid params
[[ -z $help ]] || usage 0

cache="$HOME/.cache/burp"
mkdir -p "$cache"

# Ensure json config exists
[[ -f "$cache/burp.json" ]] || echo "{}" >"$cache/burp.json"

# Clear cached BurpSuite if requested
[[ -z $clear ]] || find "$cache" -name "*.jar" -exec rm -f {} +

# Get BurpSuite if missing
burpsuite="$(find "$cache" -name "burp*.jar" | sort -nr | head -n 1)"
if [[ -z $burpsuite ]]; then
    url="https://portswigger.net/burp/releases/download"
    query="?type=jar&product=community"

    curl -Lo "$cache/burpsuite_community.jar" "$url$query"
    [[ $? -eq 0 ]] || errx 1 "Failed to download burpsuite jar"

    burpsuite="$cache/burpsuite_community.jar"
fi

java -jar "$burpsuite" --config-file="$cache/burp.json" "$@"
