#!/usr/bin/env bash

# Make it so anyone can run nmap (or whatever), not just root
tool="${1:-/usr/bin/nmap}"

if [[ -f $tool ]]; then
    sudo setcap cap_net_admin,cap_net_bind_service,cap_net_raw+eip \
        $tool
else
    echo "$tool not found"
fi
