#!/usr/bin/env bash

err() { echo -e "${color:+\e[31m}[!] $@\e[0m"; }

errx() { echo -e "${color:+\e[31m}[!] ${@:2}\e[0m"; exit $1; }

ftp_delete() {
    [[ $# -eq 1 ]] || usage 4

    ftp -inv $host <<EOF
user $user $pass
delete $1
bye
EOF
}

ftp_get() {
    [[ $# -eq 1 ]] || usage 5

    ftp -inv $host <<EOF
user $user $pass
get $1 $$(basename $1)
bye
EOF
}

ftp_upload() {
    [[ $# -eq 2 ]] || usage 6

    ftp -inv $host <<EOF
user $user $pass
mkdir $(dirname $2)
bin
put $1 $2
bye
EOF
}

good() { echo -e "${color:+\e[32m}[+] $@\e[0m"; }

info() { echo -e "${color:+\e[37m}[*] $@\e[0m"; }

long_opt() {
    local arg shift="0"
    case "$1" in
        "--"*"="*) arg="${1#*=}"; [[ -n $arg ]] || usage 1 ;;
        *) shift="1"; shift; [[ $# -gt 0 ]] || usage 1; arg="$1" ;;
    esac
    echo "$arg"
    return $shift
}

usage() {
    echo "Usage: ${0/*\//} [OPTIONS] <host> <user> <pass> ..."
    echo
    echo "FTP tool for easy scripting"
    echo
    echo "Options:"
    echo "    -d, --delete    Delete file on ftp server"
    echo "    -g, --get       Get file from ftp server"
    echo "    -h, --help      Display this help message"
    echo "    -u, --upload    Upload file to ftp server"
    echo
    echo "Examples:"
    echo "    ftp_util --upload host user pass file wwwroot/file"
    echo "    ftp_util --delete host user pass wwwroot/file"
    echo "    ftp_util --get host user pass wwwroot/file"
    echo
    exit $1
}

warn() { echo -e "${color:+\e[33m}[-] $@\e[0m"; }

declare -a args
unset action help
color="true"

# Parse command line options
while [[ $# -gt 0 ]]; do
    case "$1" in
        "--") shift && args+=("$@") && break ;;
        "-d"|"--delete") action="delete" ;;
        "-g"|"--get") action="get" ;;
        "-h"|"--help") help="true" ;;
        "-u"|"--upload") action="upload" ;;
        *) args+=("$1") ;;
    esac
    shift
done
[[ -z ${args[@]} ]] || set -- "${args[@]}"

# Check for valid params and missing dependencies
[[ -z $help ]] || usage 0
[[ $# -ge 3 ]] || usage 1
for dep in ftp; do
    [[ -n $(command -v $dep) ]] || errx 2 "$dep is not installed"
done; unset dep
[[ -n $action ]] || usage 3

host="$1" && shift
user="$1" && shift
pass="$1" && shift

case "$action" in
    "delete") ftp_delete $@ ;;
    "get") ftp_get $@ ;;
    "upload") ftp_upload $@ ;;
esac
