#!/usr/bin/env bash

### Helpers begin
check_deps() {
    local missing
    for d in "${deps[@]}"; do
        if [[ -z $(command -v "$d") ]]; then
            # Force absolute path
            if [[ ! -e "/$d" ]]; then
                err "$d was not found"
                missing="true"
            fi
        fi
    done; unset d
    [[ -z $missing ]] || exit 128
}
err() { echo -e "${color:+\e[31m}[!] $*\e[0m"; }
errx() { err "${*:2}"; exit "$1"; }
good() { echo -e "${color:+\e[32m}[+] $*\e[0m"; }
info() { echo -e "${color:+\e[37m}[*] $*\e[0m"; }
long_opt() {
    local arg shift="0"
    case "$1" in
        "--"*"="*) arg="${1#*=}"; [[ -n $arg ]] || return 127 ;;
        *) shift="1"; shift; [[ $# -gt 0 ]] || return 127; arg="$1" ;;
    esac
    echo "$arg"
    return $shift
}
subinfo() { echo -e "${color:+\e[36m}[=] $*\e[0m"; }
warn() { echo -e "${color:+\e[33m}[-] $*\e[0m"; }
### Helpers end

ftp_delete() {
    [[ $# -eq 1 ]] || usage 3

    ftp -inv $host <<EOF
user $user $pass
delete $1
bye
EOF
}

ftp_get() {
    [[ $# -eq 1 ]] || usage 4

    ftp -inv $host <<EOF
user $user $pass
get $1 $$(basename $1)
bye
EOF
}

ftp_upload() {
    [[ $# -eq 2 ]] || usage 5

    ftp -inv $host <<EOF
user $user $pass
mkdir $(dirname $2)
bin
put $1 $2
bye
EOF
}

usage() {
    cat <<EOF
Usage: ${0##*/} [OPTIONS] <host> <user> <pass> ...

DESCRIPTION
    FTP tool for easy scripting.

OPTIONS
    -d, --delete    Delete file on ftp server
    -g, --get       Get file from ftp server
    -h, --help      Display this help message
    -u, --upload    Upload file to ftp server

EXAMPLES
    ftp_util --upload host user pass file wwwroot/file
    ftp_util --delete host user pass wwwroot/file
    ftp_util --get host user pass wwwroot/file

EOF
    exit "$1"
}

declare -a args
unset action help
color="true"

# Parse command line options
while [[ $# -gt 0 ]]; do
    case "$1" in
        "--") shift; args+=("$@"); break ;;
        "-d"|"--delete") action="delete" ;;
        "-g"|"--get") action="get" ;;
        "-h"|"--help") help="true" ;;
        "--no-color") unset color ;;
        "-u"|"--upload") action="upload" ;;
        *) args+=("$1") ;;
    esac
    case "$?" in
        0) ;;
        1) shift ;;
        *) usage $? ;;
    esac
    shift
done
[[ ${#args[@]} -eq 0 ]] || set -- "${args[@]}"

# Help info
[[ -z $help ]] || usage 0

# Check for missing dependencies
declare -a deps
deps+=("ftp")
check_deps

# Check for valid params
[[ $# -ge 3 ]] || usage 1
[[ -n $action ]] || usage 1

host="$1"
user="$2"
pass="$3"
shift 3

case "$action" in
    "delete") ftp_delete $@ ;;
    "get") ftp_get $@ ;;
    "upload") ftp_upload $@ ;;
esac
