#!/usr/bin/env bash
# A script for making some iptables commands easier.
# by Miles Whittaker <mjwhitta@gmail.com>
#
# --------------------------------------------------------------------
# The MIT License (MIT)
#
# Copyright (c) 2018 Miles Whittaker
#
# Permission is hereby granted, free of charge, to any person
# obtaining a copy of this software and associated documentation files
# (the "Software"), to deal in the Software without restriction,
# including without limitation the rights to use, copy, modify, merge,
# publish, distribute, sublicense, and/or sell copies of the Software,
# and to permit persons to whom the Software is furnished to do so,
# subject to the following conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
# BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
# ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
# --------------------------------------------------------------------

### Helpers begin
check_deps() {
    for d in "${deps[@]}"; do
        [[ -n $(command -v "$d") ]] || errx 128 "$d is not installed"
    done; unset d
}
err() { echo -e "${color:+\e[31m}[!] $*\e[0m"; }
errx() { echo -e "${color:+\e[31m}[!] ${*:2}\e[0m"; exit "$1"; }
good() { echo -e "${color:+\e[32m}[+] $*\e[0m"; }
info() { echo -e "${color:+\e[37m}[*] $*\e[0m"; }
long_opt() {
    local arg shift="0"
    case "$1" in
        "--"*"="*) arg="${1#*=}"; [[ -n $arg ]] || usage 127 ;;
        *) shift="1"; shift; [[ $# -gt 0 ]] || usage 127; arg="$1" ;;
    esac
    echo "$arg"
    return $shift
}
subinfo() { echo -e "${color:+\e[36m}[=] $*\e[0m"; }
warn() { echo -e "${color:+\e[33m}[-] $*\e[0m"; }
### Helpers end

fw_clear() {
    # Save Docker rules
    sudo "${iptables}-save" | grep -iPs "^\*|^commit$|$dreg" \
        >/tmp/fw.docker.rules

    for tbl in "${tbls[@]}"; do
        while read -r chain; do
            sudo "$iptables" -t "$tbl" -P "$chain" ACCEPT
        done < <(
            sudo "$iptables" -S -t "$tbl" | awk '/-P/ {print $2}'
        ); unset chain
        sudo "$iptables" -t "$tbl" -F
        while read -r chain; do
            sudo "$iptables" -t "$tbl" -X "$chain"
        done < <(
            sudo "$iptables" -S -t "$tbl" | awk '/-N/ {print $2}'
        ); unset chain
    done; unset tbl

    # Restore Docker rules
    sudo cat /tmp/fw.docker.rules | sudo "${iptables}-restore"
    sudo rm -f /tmp/fw.docker.rules
}

fw_close() {
    sudo "$iptables" -D INPUT -p tcp --dport "$1" -j ACCEPT
    sudo "$iptables" -D INPUT -p udp --dport "$1" -j ACCEPT
}

fw_list() {
    for tbl in "${tbls[@]}"; do
        info "$tbl"
        if [[ $# -eq 0 ]]; then
            sudo "$iptables" -S -t "$tbl" | grep -iPsv "$dreg"
        else
            sudo "$iptables" -S -t "$tbl"
        fi
    done; unset tbl
}

fw_open() {
    sudo "$iptables" -I INPUT -p tcp --dport "$1" -j ACCEPT
    sudo "$iptables" -I INPUT -p udp --dport "$1" -j ACCEPT
}

fw_reset() {
    if [[ -f "/etc/iptables/$iptables.rules" ]]; then
        fw_clear
        sudo cat "/etc/iptables/$iptables.rules" | \
            sudo "${iptables}-restore" -n
    fi
}

join_with() { local IFS="$1"; echo "${*:2}"; }

usage() {
    cat <<EOF
Usage: ${0##*/} [OPTIONS]

Makes some $iptables commands easier.

Options:
    -a, --all           Include Docker rules in output
    -h, --help          Display this help message
    -c, --close=PORT    Close a previously opened port
    --clear             Clear $iptables rules
    -l, --list          List $iptables rules (default behavior)
    --nocolor           Disable colorized output
    -o, --open=PORT     Open a port
    -r, --reset         Restore default $iptables rules

EOF
    exit "$1"
}

# Enable multi-call functionality
unset iptables
case "${0##*/}" in
    *"6") iptables="ip6tables" ;;
esac

declare -a args deps tbls
unset all help port
action="list"
color="true"
deps+=("${iptables:-iptables}")
tbls+=("filter")
while read -r tbl; do
    [[ "$tbl" == "filter" ]] || tbls+=("$tbl")
done < <(lsmod | grep -ioPs "^ip${iptables:+6}table_\K\S+" | sort)
iptables="${iptables:-iptables}"

# Check for missing dependencies
check_deps

# Parse command line options
while [[ $# -gt 0 ]]; do
    case "$1" in
        "--") shift && args+=("$@") && break ;;
        "-a"|"--all") all="true" ;;
        "--clear") action="clear" ;;
        "-c"|"--close"*)
            action="close"
            port="$(long_opt "$@")" || shift
            ;;
        "-h"|"--help") help="true" ;;
        "-l"|"--list") action="list" ;;
        "--nocolor") unset color ;;
        "-o"|"--open"*)
            action="open"
            port="$(long_opt "$@")" || shift
            ;;
        "-r"|"--reset") action="reset" ;;
        *) args+=("$1") ;;
    esac
    shift
done
[[ ${#args[@]} -eq 0 ]] || set -- "${args[@]}"

# Check for valid params
[[ -z $help ]] || usage 0
[[ $# -eq 0 ]] || usage 1

declare -a dignore
if [[ -n $(command -v docker) ]]; then
    # Ignore Docker interfaces
    while read -r dint; do
        dignore+=("$dint")
    done < <(ip -o a | grep -ioPs "\d+:\s+\Kdocker\d+"); unset dint

    # Ignore Docker networks
    while read -r dnet; do
        dignore+=("br-$dnet")
    done < <(sudo docker network list -q); unset dnet

    # Ignore Docker IPs
    if [[ ${#dignore[@]} -gt 0 ]]; then
        dreg="$(join_with "|" "${dignore[@]}")"
        while read -r dip; do
            dignore+=("$dip")
        done < <(
            ip -o a | grep -ioPs "($dreg)\s+inet\s+\K(\d{1,3}\.){3}"
        ); unset dip
        unset dreg
    fi
fi
dignore+=("docker")
dreg="$(join_with "|" "${dignore[@]}")"

case "$action" in
    "close") fw_close "$port" ;;
    "clear") fw_clear ;;
    "list") fw_list $all ;;
    "open") fw_open "$port" ;;
    "reset") fw_reset ;;
esac
