#!/usr/bin/env bash
# A script for generating /etc/passwd entries.
# by Miles Whittaker <mjwhitta@gmail.com>
#
# --------------------------------------------------------------------
# The MIT License (MIT)
#
# Copyright (c) 2018 Miles Whittaker
#
# Permission is hereby granted, free of charge, to any person
# obtaining a copy of this software and associated documentation files
# (the "Software"), to deal in the Software without restriction,
# including without limitation the rights to use, copy, modify, merge,
# publish, distribute, sublicense, and/or sell copies of the Software,
# and to permit persons to whom the Software is furnished to do so,
# subject to the following conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
# BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
# ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
# --------------------------------------------------------------------

function gen_passwd_entry() {
    if [[ -z $(command -v makepasswd) ]]; then
        echo "makepasswd is not installed"
        return 3
    fi

    gpe_cleanup() {
        unset arg args help noblock passwd
        unset -f gpe_cleanup gpe_usage
    }

    gpe_usage() {
        echo "Usage: gen_passwd_entry [OPTIONS] <username>"
        echo
        echo "Generate /etc/passwd entries"
        echo
        echo "Options:"
        echo "    -h, --help             Display this help message"
        echo "    -n, --noblock          Don't use blocking random"
        echo "    -p, --passwd=PASSWD    Use specified password"
        echo
        gpe_cleanup
    }

    declare -a args
    unset help noblock passwd

    while [[ $# -gt 0 ]]; do
        case "$1" in
            "--") shift && args+=("$@") && break ;;
            "-h"|"--help") help="true" ;;
            "-n"|"--noblock") noblock="true" ;;
            "-p"|"--passwd"*)
                case "$1" in
                    "--"*"="*)
                        arg="${1#*=}"
                        [[ -z $arg ]] && gpe_usage && return 1
                        ;;
                    *)
                        shift; [[ $# -eq 0 ]] && gpe_usage && return 1
                        arg="$1"
                        ;;
                esac
                passwd="$arg"
                ;;
            *) args+=("$1") ;;
        esac
        shift
    done
    [[ -z ${args[@]} ]] || set -- "${args[@]}"

    [[ -n $help ]] && gpe_usage && return 0
    [[ $# -ne 1 ]] && gpe_usage && return 2
    [[ -n $passwd ]] || passwd="$1"

    echo -n "$1"
    if [[ -z $noblock ]];  then
        makepasswd --clearfrom=<(echo "$passwd") --crypt-md5 | \
            awk '{print ":"$2":0:0:::"}'
    else
        makepasswd --clearfrom=<(echo "$passwd") --crypt-md5 \
            --randomseed 1 | awk '{print ":"$2":0:0:::"}'
    fi

    gpe_cleanup
}

if [[ -n ${BASH_SOURCE[0]} ]]; then
    case "$0" in
        *"bash") ;;
        *) gen_passwd_entry "$@" ;;
    esac
fi
