#!/usr/bin/env bash
# A script for generating /etc/passwd entries.
# by Miles Whittaker <mj@whitta.dev>
#
# --------------------------------------------------------------------
# The MIT License (MIT)
#
# Copyright (c) 2020 Miles Whittaker
#
# Permission is hereby granted, free of charge, to any person
# obtaining a copy of this software and associated documentation files
# (the "Software"), to deal in the Software without restriction,
# including without limitation the rights to use, copy, modify, merge,
# publish, distribute, sublicense, and/or sell copies of the Software,
# and to permit persons to whom the Software is furnished to do so,
# subject to the following conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
# BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
# ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
# --------------------------------------------------------------------

### Helpers begin
check_deps() {
    local missing
    for d in "${deps[@]}"; do
        if [[ -z $(command -v "$d") ]]; then
            # Force absolute path
            if [[ ! -e "/$d" ]]; then
                err "$d was not found"
                missing="true"
            fi
        fi
    done; unset d
    [[ -z $missing ]] || exit 128
}
err() { echo -e "${color:+\e[31m}[!] $*\e[0m"; }
errx() { err "${*:2}"; exit "$1"; }
good() { echo -e "${color:+\e[32m}[+] $*\e[0m"; }
info() { echo -e "${color:+\e[37m}[*] $*\e[0m"; }
long_opt() {
    local arg shift="0"
    case "$1" in
        "--"*"="*) arg="${1#*=}"; [[ -n $arg ]] || return 127 ;;
        *) shift="1"; shift; [[ $# -gt 0 ]] || return 127; arg="$1" ;;
    esac
    echo "$arg"
    return $shift
}
subinfo() { echo -e "${color:+\e[36m}[=] $*\e[0m"; }
warn() { echo -e "${color:+\e[33m}[-] $*\e[0m"; }
### Helpers end

genpasswd() {
    case "$2" in
        "x") echo "$1:x:1000:1000::/home/$1:/bin/bash" ;;
        *) echo "$1:$(makepwd "${2:-$1}"):1000:1000::/home/$1:/bin/bash" ;;
    esac
}

genshadow() {
    local epoch="$(($(date +%s)/60/60/24))"

    case "$2" in
        "!") echo "$1:!:$epoch:0:99999:7:::" ;;
        *) echo "$1:$(makepwd "${2:-$1}"):$epoch:0:99999:7:::" ;;
    esac
}

makepwd() {
    if makepasswd -h 2>/dev/null | grep -q -s "GNU"; then
        makepasswd --clearfrom=<(echo "$1") --crypt-md5 | \
            awk '{print $2}'
    else
        makepasswd -e sha256 -p "$1" | awk '{print $2}'
    fi
}

usage() {
    cat <<EOF
Usage: ${0##*/} [OPTIONS] <username>

DESCRIPTION
    Generate /etc/passwd or /etc/shadow entries.

OPTIONS
    -h, --help             Display this help message
    --no-color             Disable colorized output
    -p, --passwd=PASSWD    Use specified password
    -s, --shadow           Generate shadow file entry

EOF
    exit "$1"
}

declare -a args
unset help passwd shadow
color="true"

# Parse command line options
while [[ $# -gt 0 ]]; do
    case "$1" in
        "--") shift; args+=("$@"); break ;;
        "-h"|"--help") help="true" ;;
        "--no-color") unset color ;;
        "-p"|"--passwd"*) passwd="$(long_opt "$@")" ;;
        "-s"|"--shadow") shadow="true" ;;
        *) args+=("$1") ;;
    esac
    case "$?" in
        0) ;;
        1) shift ;;
        *) usage $? ;;
    esac
    shift
done
[[ ${#args[@]} -eq 0 ]] || set -- "${args[@]}"

# Help info
[[ -z $help ]] || usage 0

# Check for missing dependencies
declare -a deps
deps+=("awk")
deps+=("makepasswd")
check_deps

# Check for valid params
[[ $# -eq 1 ]] || usage 1

if [[ -n $shadow ]]; then
    genshadow "$1" "${passwd:-$1}"
else
    genpasswd "$1" "${passwd:-$1}"
fi

