#!/usr/bin/env bash

### Helpers begin
check_deps() {
    local missing
    for d in "${deps[@]}"; do
        if [[ -z $(command -v "$d") ]]; then
            # Force absolute path
            if [[ ! -e "/$d" ]]; then
                err "$d was not found"
                missing="true"
            fi
        fi
    done; unset d
    [[ -z $missing ]] || exit 128
}
err() { echo -e "${color:+\e[31m}[!] $*\e[0m"; }
errx() { err "${*:2}"; exit "$1"; }
good() { echo -e "${color:+\e[32m}[+] $*\e[0m"; }
info() { echo -e "${color:+\e[37m}[*] $*\e[0m"; }
long_opt() {
    local arg shift="0"
    case "$1" in
        "--"*"="*) arg="${1#*=}"; [[ -n $arg ]] || return 127 ;;
        *) shift="1"; shift; [[ $# -gt 0 ]] || return 127; arg="$1" ;;
    esac
    echo "$arg"
    return $shift
}
subinfo() { echo -e "${color:+\e[36m}[=] $*\e[0m"; }
warn() { echo -e "${color:+\e[33m}[-] $*\e[0m"; }
### Helpers end

usage() {
    cat <<EOF
Usage: ${0##*/} [OPTIONS]

DESCRIPTION
    Launch JADX.

OPTIONS
    -c, --clear    Clear cache and download the newest JADX
    -g, --gui      Launch the GUI
    -h, --help     Display this help message
    --no-color     Disable colorized output

EOF
    exit "$1"
}

declare -a args
unset clear gui help
color="true"

# Parse command line options
while [[ $# -gt 0 ]]; do
    case "$1" in
        "--") shift; args+=("$@"); break ;;
        "-c"|"--clear") clear="true" ;;
        "-g"|"--gui") gui="true" ;;
        "-h"|"--help") help="true" ;;
        "--no-color") unset color ;;
        *) args+=("$1") ;;
    esac
    case "$?" in
        0) ;;
        1) shift ;;
        *) usage $? ;;
    esac
    shift
done
[[ ${#args[@]} -eq 0 ]] || set -- "${args[@]}"

# Help info
[[ -z $help ]] || usage 0

# Check for missing dependencies
declare -a deps
deps+=("curl")
deps+=("java")
deps+=("unzip")
check_deps

# TODO Check for valid params

cache="$HOME/.cache/jadx"
mkdir -p "$cache"

# Clear cached JADX if requested
# shellcheck disable=SC2115
[[ -z $clear ]] || rm -fr "$cache"/*

# Get JADX if missing
jd="$(find "$cache" -name "jadx*.zip" | sort -nr | head -n 1)"
if [[ -z $jd ]]; then
    url="https://github.com"
    path="/skylot/jadx/releases"

    path="$(
        curl -Ls "$url$path" | \
        grep -ioPs "href\=.\K.+jadx.+\d\.\d\.\d\.zip" | head -n 1
    )"
    [[ -n $path ]] || errx 1 "Failed to find JADX zip"

    name="$(basename "$path")"
    curl -Lo "$cache/$name" "$url$path"
    [[ $? -eq 0 ]] || errx 1 "Failed to download JADX zip"

    jd="$(find "$cache" -name "jadx*.zip" | sort -nr | head -n 1)"
    unzip -d "$cache" "$jd"
fi

[[ -z $gui ]] || "$cache/bin/jadx-gui" "$@"
[[ -n $gui ]] || "$cache/bin/jadx" "$@"
