#!/usr/bin/env bash

set -o noglob

cache_default_lists() {
    # Create dcache directory
    mkdir -p $(dirname $dcache)
    rm -f $dcache

    local dirb_blist="big.txt"
    local dirb_clist="common.txt"
    local dirbuster_list="directory-list-2.3-medium.txt"
    local list wordlist

    # Find dirb directory
    local dirb="$(
        find -O3 /usr -maxdepth 4 -name "dirb" -type d -print -quit \
        2>/dev/null
    )"

    # If dirb was found, find the lists
    if [[ -n $dirb ]]; then
        for list in $dirb_blist $dirb_clist; do
            wordlist="$(
                find $dirb -name "$list" -type f -print -quit \
                2>/dev/null
            )"

            # Cache location of list
            [[ -z $wordlist ]] || echo "$wordlist" >>$dcache
        done; unset list
    fi

    # Find dirbuster directory
    local dirbuster="$(
        find -O3 /usr -maxdepth 4 -name "dirbuster" -type d -print \
        -quit 2>/dev/null
    )"

    # If dirbuster was found, find the list
    if [[ -n $dirbuster ]]; then
        wordlist="$(
            find $dirbuster -name "$dirbuster_list" -type f -print \
            -quit 2>/dev/null
        )"

        # Cache location of list
        [[ -z $wordlist ]] || echo "$wordlist" >>$dcache
    fi

    touch $dcache
}

clean() {
    [[ ${1:-0} -ne 0 ]] || [[ ! -d $cache ]] || rm -rf $cache
    [[ -z $script ]] || [[ ! -f $script ]] || rm -f $script
    echo -en "\e[?25h" # Show cursor again
    exit ${1:-0}
}

err() { echo -e "${color:+\e[31m}[!] $@\e[0m"; }

errx() { echo -e "${color:+\e[31m}[!] ${@:2}\e[0m"; clean $1; }

good() { echo -e "${color:+\e[32m}[+] $@\e[0m"; }

info() { echo -e "${color:+\e[37m}[*] $@\e[0m"; }

join_with() { local IFS="$1"; echo "${*:2}"; }

json_get() {
    [[ -z $json ]] || jq -cr ".$@" $json | sed -r "s/^null$//g"
}

logo() {
    [[ -n $color ]] || return
    [[ -n $(command -v tput) ]] || return
    [[ $(tput cols) -ge 81 ]] || return
    echo
    echo -en "                       \e[38;5;232m▄\e[0m\e[38;5;232m▄"
    echo -en "\e[0m\e[48;5;232m\e[38;5;045m▄\e[0m\e[0m\e[48;5;232m\e["
    echo -en "38;5;045m▄\e[0m\e[0m\e[48;5;232m\e[38;5;045m▄\e[0m\e[0m"
    echo -en "\e[48;5;232m\e[38;5;045m▄\e[0m\e[0m\e[48;5;232m\e[38;5;"
    echo -en "045m▄\e[0m\e[0m\e[38;5;232m▄\e[0m\e[38;5;232m▄\e[0m    "
    echo -en "                         \e[7m\e[38;5;045m▄\e[0m\e[0m\e"
    echo -en "[38;5;045m▄\e[0m   \e[7m\e[38;5;033m▄\e[0m\e[0m\e[38;5;"
    echo -en "033m▄\e[0m\e[38;5;033m▄\e[0m"
    echo
    echo -en "                     \e[38;5;232m▄\e[0m\e[48;5;232m\e[3"
    echo -en "8;5;033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m"
    echo -en "\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;"
    echo -en "033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48"
    echo -en ";5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄"
    echo -en "\e[0m\e[0m\e[48;5;045m\e[38;5;033m▄\e[0m\e[0m\e[48;5;04"
    echo -en "5m\e[38;5;045m▄\e[0m\e[0m\e[48;5;045m\e[38;5;045m▄\e[0m"
    echo -en "\e[0m\e[48;5;232m\e[38;5;045m▄\e[0m\e[0m\e[38;5;232m▄\e"
    echo -en "[0m                            \e[7m\e[38;5;033m▄\e[0m"
    echo -en "\e[0m\e[48;5;045m\e[38;5;045m▄\e[0m\e[0m\e[48;5;033m\e["
    echo -en "38;5;045m▄\e[0m\e[0m\e[38;5;045m▄\e[0m \e[7m\e[38;5;033"
    echo -en "m▄\e[0m\e[0m\e[48;5;045m\e[38;5;045m▄\e[0m\e[0m\e[48;5;"
    echo -en "033m\e[38;5;045m▄\e[0m\e[0m\e[38;5;033m▄\e[0m"
    echo
    echo -en "                    \e[38;5;232m▄\e[0m\e[48;5;232m\e[38"
    echo -en ";5;033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e"
    echo -en "[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;03"
    echo -en "3m▄\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5"
    echo -en ";033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄\e"
    echo -en "[0m\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m"
    echo -en "\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;045m▄\e[0m\e"
    echo -en "[0m\e[48;5;033m\e[38;5;045m▄\e[0m\e[0m\e[48;5;033m\e[38"
    echo -en ";5;045m▄\e[0m\e[0m\e[48;5;232m\e[38;5;033m▄\e[0m\e[0m\e"
    echo -en "[38;5;232m▄\e[0m                            \e[7m\e[38;"
    echo -en "5;033m▄\e[0m\e[0m\e[48;5;045m\e[38;5;045m▄\e[0m\e[0m\e["
    echo -en "48;5;045m\e[38;5;045m▄\e[0m\e[0m\e[48;5;045m\e[38;5;045"
    echo -en "m▄\e[0m\e[0m\e[48;5;033m\e[38;5;045m▄\e[0m\e[0m\e[48;5;"
    echo -en "045m\e[38;5;045m▄\e[0m\e[0m\e[48;5;045m\e[38;5;045m▄\e["
    echo -en "0m\e[0m\e[48;5;045m\e[38;5;045m▄\e[0m\e[0m\e[48;5;033m"
    echo -en "\e[38;5;045m▄\e[0m\e[0m\e[38;5;033m▄\e[0m"
    echo
    echo -en "                    \e[48;5;232m\e[38;5;232m▄\e[0m\e[0m"
    echo -en "\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;"
    echo -en "033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48"
    echo -en ";5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄"
    echo -en "\e[0m\e[0m\e[48;5;033m\e[38;5;232m▄\e[0m\e[0m\e[48;5;03"
    echo -en "3m\e[38;5;232m▄\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m"
    echo -en "\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;045m\e["
    echo -en "38;5;045m▄\e[0m\e[0m\e[48;5;045m\e[38;5;045m▄\e[0m\e[0m"
    echo -en "\e[48;5;045m\e[38;5;045m▄\e[0m\e[0m\e[48;5;033m\e[38;5;"
    echo -en "033m▄\e[0m\e[0m\e[48;5;232m\e[38;5;232m▄\e[0m\e[0m     "
    echo -en "                \e[7m\e[38;5;033m▄\e[0m\e[0m\e[7m\e[38;"
    echo -en "5;033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e["
    echo -en "48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;033"
    echo -en "m▄\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;"
    echo -en "033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄\e["
    echo -en "0m\e[0m\e[48;5;045m\e[38;5;045m▄\e[0m\e[0m\e[48;5;045m"
    echo -en "\e[38;5;045m▄\e[0m\e[0m\e[48;5;255m\e[38;5;045m▄\e[0m\e"
    echo -en "[0m\e[48;5;045m\e[38;5;255m▄\e[0m\e[0m\e[48;5;045m\e[38"
    echo -en ";5;255m▄\e[0m\e[0m\e[48;5;045m\e[38;5;045m▄\e[0m\e[0m\e"
    echo -en "[48;5;045m\e[38;5;045m▄\e[0m\e[0m\e[48;5;033m\e[38;5;04"
    echo -en "5m▄\e[0m\e[0m\e[48;5;045m\e[38;5;033m▄\e[0m\e[0m\e[48;5"
    echo -en ";033m\e[38;5;045m▄\e[0m\e[0m\e[38;5;033m▄\e[0m"
    echo
    echo -en "                   \e[48;5;232m\e[38;5;232m▄\e[0m\e[0m"
    echo -en "\e[48;5;045m\e[38;5;045m▄\e[0m\e[0m\e[48;5;045m\e[38;5;"
    echo -en "196m▄\e[0m\e[0m\e[48;5;045m\e[38;5;045m▄\e[0m\e[0m\e[48"
    echo -en ";5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;232m▄"
    echo -en "\e[0m\e[0m\e[48;5;232m\e[38;5;223m▄\e[0m\e[0m\e[48;5;22"
    echo -en "3m\e[38;5;255m▄\e[0m\e[0m\e[48;5;255m\e[38;5;255m▄\e[0m"
    echo -en "\e[0m\e[48;5;232m\e[38;5;232m▄\e[0m\e[0m\e[48;5;033m\e["
    echo -en "38;5;232m▄\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m"
    echo -en "\e[48;5;033m\e[38;5;232m▄\e[0m\e[0m\e[48;5;232m\e[38;5;"
    echo -en "255m▄\e[0m\e[0m\e[48;5;232m\e[38;5;232m▄\e[0m\e[0m\e[7m"
    echo -en "\e[38;5;232m▄\e[0m\e[0m                      \e[38;5;03"
    echo -en "3m▄\e[0m\e[38;5;033m▄\e[0m\e[38;5;033m▄\e[0m\e[48;5;033"
    echo -en "m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;045m▄\e[0m"
    echo -en "\e[0m\e[48;5;033m\e[38;5;045m▄\e[0m\e[0m\e[48;5;045m\e["
    echo -en "38;5;045m▄\e[0m\e[0m\e[48;5;045m\e[38;5;045m▄\e[0m\e[0m"
    echo -en "\e[48;5;045m\e[38;5;255m▄\e[0m\e[0m\e[48;5;045m\e[38;5;"
    echo -en "255m▄\e[0m\e[0m\e[48;5;255m\e[38;5;255m▄\e[0m\e[0m\e[48"
    echo -en ";5;255m\e[38;5;255m▄\e[0m\e[0m\e[48;5;255m\e[38;5;255m▄"
    echo -en "\e[0m\e[0m\e[48;5;045m\e[38;5;255m▄\e[0m\e[0m\e[48;5;04"
    echo -en "5m\e[38;5;045m▄\e[0m\e[0m\e[48;5;045m\e[38;5;045m▄\e[0m"
    echo -en "\e[0m\e[48;5;033m\e[38;5;045m▄\e[0m\e[0m\e[7m\e[38;5;04"
    echo -en "5m▄\e[0m\e[0m"
    echo
    echo -en "                  \e[38;5;232m▄\e[0m\e[48;5;232m\e[38;5"
    echo -en ";232m▄\e[0m\e[0m\e[48;5;045m\e[38;5;045m▄\e[0m\e[0m\e[4"
    echo -en "8;5;196m\e[38;5;196m▄\e[0m\e[0m\e[48;5;045m\e[38;5;045m"
    echo -en "▄\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;2"
    echo -en "32m\e[38;5;232m▄\e[0m\e[0m\e[48;5;223m\e[38;5;223m▄\e[0"
    echo -en "m\e[0m\e[48;5;255m\e[38;5;255m▄\e[0m\e[0m\e[48;5;255m\e"
    echo -en "[38;5;255m▄\e[0m\e[0m\e[48;5;232m\e[38;5;232m▄\e[0m\e[0"
    echo -en "m\e[48;5;255m\e[38;5;255m▄\e[0m\e[0m\e[48;5;232m\e[38;5"
    echo -en ";223m▄\e[0m\e[0m\e[48;5;232m\e[38;5;232m▄\e[0m\e[0m\e[4"
    echo -en "8;5;255m\e[38;5;255m▄\e[0m\e[0m\e[48;5;232m\e[38;5;232m"
    echo -en "▄\e[0m\e[0m                \e[38;5;033m▄\e[0m\e[38;5;03"
    echo -en "3m▄\e[0m\e[38;5;033m▄\e[0m\e[38;5;033m▄\e[0m\e[38;5;033"
    echo -en "m▄\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m"
    echo -en "\e[38;5;033m▄\e[0m\e[0m\e[48;5;045m\e[38;5;033m▄\e[0m\e"
    echo -en "[0m\e[48;5;045m\e[38;5;033m▄\e[0m\e[0m\e[48;5;045m\e[38"
    echo -en ";5;033m▄\e[0m\e[0m\e[48;5;045m\e[38;5;045m▄\e[0m\e[0m\e"
    echo -en "[48;5;045m\e[38;5;045m▄\e[0m\e[0m\e[48;5;045m\e[38;5;25"
    echo -en "5m▄\e[0m\e[0m\e[48;5;255m\e[38;5;255m▄\e[0m\e[0m\e[48;5"
    echo -en ";255m\e[38;5;255m▄\e[0m\e[0m\e[48;5;255m\e[38;5;255m▄\e"
    echo -en "[0m\e[0m\e[48;5;255m\e[38;5;255m▄\e[0m\e[0m\e[48;5;255m"
    echo -en "\e[38;5;045m▄\e[0m\e[0m\e[48;5;045m\e[38;5;045m▄\e[0m\e"
    echo -en "[0m\e[48;5;045m\e[38;5;045m▄\e[0m\e[0m\e[48;5;045m\e[38"
    echo -en ";5;045m▄\e[0m\e[0m\e[48;5;045m\e[38;5;033m▄\e[0m\e[0m\e"
    echo -en "[48;5;045m\e[38;5;033m▄\e[0m\e[0m\e[48;5;045m\e[38;5;03"
    echo -en "3m▄\e[0m\e[0m\e[48;5;033m\e[38;5;045m▄\e[0m\e[0m\e[38;5"
    echo -en ";033m▄\e[0m\e[38;5;033m▄\e[0m\e[48;5;033m\e[38;5;033m▄"
    echo -en "\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;03"
    echo -en "3m\e[38;5;033m▄\e[0m\e[0m\e[38;5;033m▄\e[0m"
    echo
    echo -en "               \e[38;5;232m▄\e[0m\e[48;5;232m\e[38;5;04"
    echo -en "5m▄\e[0m\e[0m\e[48;5;232m\e[38;5;045m▄\e[0m\e[0m\e[48;5"
    echo -en ";045m\e[38;5;045m▄\e[0m\e[0m\e[48;5;045m\e[38;5;045m▄\e"
    echo -en "[0m\e[0m\e[48;5;232m\e[38;5;045m▄\e[0m\e[0m\e[48;5;045m"
    echo -en "\e[38;5;232m▄\e[0m\e[0m\e[48;5;045m\e[38;5;232m▄\e[0m\e"
    echo -en "[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;232m\e[38"
    echo -en ";5;232m▄\e[0m\e[0m\e[48;5;223m\e[38;5;223m▄\e[0m\e[0m\e"
    echo -en "[48;5;223m\e[38;5;223m▄\e[0m\e[0m\e[48;5;255m\e[38;5;23"
    echo -en "2m▄\e[0m\e[0m\e[48;5;255m\e[38;5;232m▄\e[0m\e[0m\e[48;5"
    echo -en ";255m\e[38;5;223m▄\e[0m\e[0m\e[48;5;223m\e[38;5;223m▄\e"
    echo -en "[0m\e[0m\e[48;5;223m\e[38;5;223m▄\e[0m\e[0m\e[48;5;223m"
    echo -en "\e[38;5;223m▄\e[0m\e[0m\e[48;5;232m\e[38;5;232m▄\e[0m\e"
    echo -en "[0m \e[38;5;232m▄\e[0m\e[48;5;232m\e[38;5;033m▄\e[0m\e["
    echo -en "0m\e[48;5;232m\e[38;5;033m▄\e[0m\e[0m\e[48;5;232m\e[38;"
    echo -en "5;033m▄\e[0m\e[0m\e[48;5;232m\e[38;5;033m▄\e[0m\e[0m\e["
    echo -en "48;5;232m\e[38;5;033m▄\e[0m\e[0m\e[48;5;232m\e[38;5;033"
    echo -en "m▄\e[0m\e[0m\e[48;5;232m\e[38;5;232m▄\e[0m\e[0m\e[38;5;"
    echo -en "232m▄\e[0m        \e[7m\e[38;5;033m▄\e[0m\e[0m\e[7m\e[3"
    echo -en "8;5;033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m"
    echo -en "\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;"
    echo -en "033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48"
    echo -en ";5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;045m▄"
    echo -en "\e[0m\e[0m\e[48;5;033m\e[38;5;045m▄\e[0m\e[0m\e[48;5;04"
    echo -en "5m\e[38;5;255m▄\e[0m\e[0m\e[48;5;045m\e[38;5;255m▄\e[0m"
    echo -en "\e[0m\e[48;5;045m\e[38;5;255m▄\e[0m\e[0m\e[48;5;255m\e["
    echo -en "38;5;231m▄\e[0m\e[0m\e[48;5;255m\e[38;5;231m▄\e[0m\e[0m"
    echo -en "\e[48;5;045m\e[38;5;255m▄\e[0m\e[0m\e[48;5;045m\e[38;5;"
    echo -en "255m▄\e[0m\e[0m\e[48;5;045m\e[38;5;045m▄\e[0m\e[0m\e[48"
    echo -en ";5;045m\e[38;5;045m▄\e[0m\e[0m\e[38;5;045m▄\e[0m\e[38;5"
    echo -en ";045m▄\e[0m \e[38;5;033m▄\e[0m\e[38;5;033m▄\e[0m\e[38;5"
    echo -en ";033m▄\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;0"
    echo -en "33m\e[38;5;033m▄\e[0m\e[0m\e[48;5;045m\e[38;5;045m▄\e[0"
    echo -en "m\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e"
    echo -en "[38;5;033m▄\e[0m\e[0m"
    echo
    echo -en "             \e[38;5;232m▄\e[0m\e[48;5;232m\e[38;5;033m"
    echo -en "▄\e[0m\e[0m\e[48;5;232m\e[38;5;033m▄\e[0m\e[0m\e[48;5;2"
    echo -en "32m\e[38;5;033m▄\e[0m\e[0m\e[48;5;232m\e[38;5;033m▄\e[0"
    echo -en "m\e[0m\e[48;5;045m\e[38;5;232m▄\e[0m\e[0m\e[48;5;045m\e"
    echo -en "[38;5;045m▄\e[0m\e[0m\e[48;5;045m\e[38;5;045m▄\e[0m\e[0"
    echo -en "m\e[48;5;045m\e[38;5;045m▄\e[0m\e[0m\e[48;5;232m\e[38;5"
    echo -en ";033m▄\e[0m\e[0m\e[48;5;232m\e[38;5;232m▄\e[0m\e[0m\e[4"
    echo -en "8;5;033m\e[38;5;232m▄\e[0m\e[0m\e[48;5;232m\e[38;5;033m"
    echo -en "▄\e[0m\e[0m\e[48;5;223m\e[38;5;232m▄\e[0m\e[0m\e[48;5;2"
    echo -en "23m\e[38;5;223m▄\e[0m\e[0m\e[48;5;223m\e[38;5;223m▄\e[0"
    echo -en "m\e[0m\e[48;5;232m\e[38;5;223m▄\e[0m\e[0m\e[48;5;223m\e"
    echo -en "[38;5;223m▄\e[0m\e[0m\e[48;5;223m\e[38;5;223m▄\e[0m\e[0"
    echo -en "m\e[48;5;223m\e[38;5;232m▄\e[0m\e[0m\e[48;5;232m\e[38;5"
    echo -en ";045m▄\e[0m\e[0m\e[48;5;232m\e[38;5;232m▄\e[0m\e[0m\e[4"
    echo -en "8;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;033m"
    echo -en "▄\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;0"
    echo -en "33m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄\e[0"
    echo -en "m\e[0m\e[48;5;033m\e[38;5;232m▄\e[0m\e[0m\e[48;5;232m\e"
    echo -en "[38;5;045m▄\e[0m\e[0m\e[48;5;045m\e[38;5;196m▄\e[0m\e[0"
    echo -en "m\e[48;5;045m\e[38;5;232m▄\e[0m\e[0m\e[48;5;232m\e[38;5"
    echo -en ";045m▄\e[0m\e[0m\e[38;5;232m▄\e[0m     \e[38;5;033m▄\e["
    echo -en "0m\e[38;5;033m▄\e[0m\e[38;5;045m▄\e[0m\e[38;5;045m▄\e[0"
    echo -en "m\e[48;5;033m\e[38;5;045m▄\e[0m\e[0m\e[48;5;033m\e[38;5"
    echo -en ";255m▄\e[0m\e[0m\e[48;5;045m\e[38;5;255m▄\e[0m\e[0m\e[4"
    echo -en "8;5;045m\e[38;5;255m▄\e[0m\e[0m\e[48;5;045m\e[38;5;255m"
    echo -en "▄\e[0m\e[0m\e[48;5;255m\e[38;5;231m▄\e[0m\e[0m\e[48;5;2"
    echo -en "55m\e[38;5;231m▄\e[0m\e[0m\e[48;5;231m\e[38;5;231m▄\e[0"
    echo -en "m\e[0m\e[48;5;231m\e[38;5;231m▄\e[0m\e[0m\e[48;5;231m\e"
    echo -en "[38;5;231m▄\e[0m\e[0m\e[48;5;231m\e[38;5;231m▄\e[0m\e[0"
    echo -en "m\e[48;5;231m\e[38;5;231m▄\e[0m\e[0m\e[48;5;231m\e[38;5"
    echo -en ";255m▄\e[0m\e[0m\e[48;5;231m\e[38;5;255m▄\e[0m\e[0m\e[4"
    echo -en "8;5;231m\e[38;5;045m▄\e[0m\e[0m\e[48;5;255m\e[38;5;045m"
    echo -en "▄\e[0m\e[0m\e[7m\e[38;5;255m▄\e[0m\e[0m\e[48;5;045m\e[3"
    echo -en "8;5;033m▄\e[0m\e[0m\e[48;5;045m\e[38;5;045m▄\e[0m\e[0m"
    echo -en "\e[48;5;045m\e[38;5;045m▄\e[0m\e[0m\e[48;5;045m\e[38;5;"
    echo -en "255m▄\e[0m\e[0m\e[48;5;045m\e[38;5;255m▄\e[0m\e[0m\e[48"
    echo -en ";5;045m\e[38;5;045m▄\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄"
    echo -en "\e[0m\e[0m\e[48;5;045m\e[38;5;045m▄\e[0m\e[0m\e[48;5;03"
    echo -en "3m\e[38;5;033m▄\e[0m\e[0m"
    echo
    echo -en "             \e[48;5;232m\e[38;5;232m▄\e[0m\e[0m\e[48;5"
    echo -en ";033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄\e"
    echo -en "[0m\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m"
    echo -en "\e[38;5;232m▄\e[0m\e[0m\e[48;5;232m\e[38;5;033m▄\e[0m\e"
    echo -en "[0m\e[48;5;232m\e[38;5;033m▄\e[0m\e[0m\e[48;5;232m\e[38"
    echo -en ";5;033m▄\e[0m\e[0m\e[48;5;045m\e[38;5;232m▄\e[0m\e[0m\e"
    echo -en "[48;5;045m\e[38;5;045m▄\e[0m\e[0m\e[48;5;033m\e[38;5;04"
    echo -en "5m▄\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5"
    echo -en ";232m\e[38;5;033m▄\e[0m\e[0m\e[48;5;232m\e[38;5;033m▄\e"
    echo -en "[0m\e[0m\e[48;5;232m\e[38;5;033m▄\e[0m\e[0m\e[48;5;232m"
    echo -en "\e[38;5;045m▄\e[0m\e[0m\e[48;5;232m\e[38;5;045m▄\e[0m\e"
    echo -en "[0m\e[48;5;232m\e[38;5;045m▄\e[0m\e[0m\e[48;5;232m\e[38"
    echo -en ";5;045m▄\e[0m\e[0m\e[48;5;045m\e[38;5;045m▄\e[0m\e[0m\e"
    echo -en "[48;5;045m\e[38;5;045m▄\e[0m\e[0m\e[48;5;232m\e[38;5;23"
    echo -en "2m▄\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5"
    echo -en ";033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄\e"
    echo -en "[0m\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m"
    echo -en "\e[38;5;033m▄\e[0m\e[0m\e[48;5;232m\e[38;5;232m▄\e[0m\e"
    echo -en "[0m\e[48;5;045m\e[38;5;045m▄\e[0m\e[0m\e[48;5;196m\e[38"
    echo -en ";5;196m▄\e[0m\e[0m\e[48;5;232m\e[38;5;232m▄\e[0m\e[0m\e"
    echo -en "[48;5;045m\e[38;5;045m▄\e[0m\e[0m\e[48;5;232m\e[38;5;23"
    echo -en "2m▄\e[0m\e[0m \e[7m\e[38;5;033m▄\e[0m\e[0m\e[7m\e[38;5;"
    echo -en "033m▄\e[0m\e[0m\e[7m\e[38;5;033m▄\e[0m\e[0m\e[7m\e[38;5"
    echo -en ";045m▄\e[0m\e[0m\e[48;5;045m\e[38;5;033m▄\e[0m\e[0m\e[4"
    echo -en "8;5;255m\e[38;5;033m▄\e[0m\e[0m\e[48;5;255m\e[38;5;045m"
    echo -en "▄\e[0m\e[0m\e[48;5;231m\e[38;5;045m▄\e[0m\e[0m\e[48;5;2"
    echo -en "31m\e[38;5;045m▄\e[0m\e[0m\e[48;5;231m\e[38;5;255m▄\e[0"
    echo -en "m\e[0m\e[48;5;231m\e[38;5;255m▄\e[0m\e[0m\e[48;5;231m\e"
    echo -en "[38;5;255m▄\e[0m\e[0m\e[48;5;231m\e[38;5;255m▄\e[0m\e[0"
    echo -en "m\e[48;5;231m\e[38;5;231m▄\e[0m\e[0m\e[48;5;231m\e[38;5"
    echo -en ";231m▄\e[0m\e[0m\e[48;5;231m\e[38;5;231m▄\e[0m\e[0m\e[4"
    echo -en "8;5;231m\e[38;5;231m▄\e[0m\e[0m\e[48;5;231m\e[38;5;231m"
    echo -en "▄\e[0m\e[0m\e[48;5;255m\e[38;5;231m▄\e[0m\e[0m\e[48;5;0"
    echo -en "45m\e[38;5;231m▄\e[0m\e[0m\e[48;5;045m\e[38;5;255m▄\e[0"
    echo -en "m\e[0m\e[48;5;045m\e[38;5;255m▄\e[0m\e[0m\e[38;5;045m▄"
    echo -en "\e[0m\e[38;5;045m▄\e[0m \e[48;5;033m\e[38;5;033m▄\e[0m"
    echo -en "\e[0m\e[48;5;045m\e[38;5;045m▄\e[0m\e[0m\e[48;5;255m\e["
    echo -en "38;5;045m▄\e[0m\e[0m\e[48;5;255m\e[38;5;255m▄\e[0m\e[0m"
    echo -en "\e[48;5;255m\e[38;5;255m▄\e[0m\e[0m\e[48;5;255m\e[38;5;"
    echo -en "045m▄\e[0m\e[0m\e[48;5;045m\e[38;5;033m▄\e[0m\e[0m\e[48"
    echo -en ";5;045m\e[38;5;045m▄\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄"
    echo -en "\e[0m\e[0m"
    echo
    echo -en "             \e[48;5;232m\e[38;5;232m▄\e[0m\e[0m\e[48;5"
    echo -en ";033m\e[38;5;232m▄\e[0m\e[0m\e[48;5;033m\e[38;5;232m▄\e"
    echo -en "[0m\e[0m\e[48;5;232m\e[38;5;033m▄\e[0m\e[0m\e[48;5;232m"
    echo -en "\e[38;5;232m▄\e[0m\e[0m\e[48;5;033m\e[38;5;232m▄\e[0m\e"
    echo -en "[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e[38"
    echo -en ";5;033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e"
    echo -en "[48;5;232m\e[38;5;232m▄\e[0m\e[0m\e[48;5;045m\e[38;5;04"
    echo -en "5m▄\e[0m\e[0m\e[48;5;045m\e[38;5;045m▄\e[0m\e[0m\e[48;5"
    echo -en ";045m\e[38;5;045m▄\e[0m\e[0m\e[48;5;045m\e[38;5;045m▄\e"
    echo -en "[0m\e[0m\e[48;5;045m\e[38;5;045m▄\e[0m\e[0m\e[48;5;045m"
    echo -en "\e[38;5;232m▄\e[0m\e[0m\e[7m\e[38;5;232m▄\e[0m\e[0m\e[7"
    echo -en "m\e[38;5;232m▄\e[0m\e[0m\e[7m\e[38;5;232m▄\e[0m\e[0m\e["
    echo -en "7m\e[38;5;232m▄\e[0m\e[0m\e[7m\e[38;5;232m▄\e[0m\e[0m\e"
    echo -en "[7m\e[38;5;232m▄\e[0m\e[0m\e[48;5;033m\e[38;5;232m▄\e[0"
    echo -en "m\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e"
    echo -en "[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0"
    echo -en "m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e[38;5"
    echo -en ";033m▄\e[0m\e[0m\e[48;5;232m\e[38;5;033m▄\e[0m\e[0m\e[4"
    echo -en "8;5;045m\e[38;5;232m▄\e[0m\e[0m\e[48;5;045m\e[38;5;232m"
    echo -en "▄\e[0m\e[0m\e[7m\e[38;5;232m▄\e[0m\e[0m         \e[38;5"
    echo -en ";033m▄\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;0"
    echo -en "33m\e[38;5;033m▄\e[0m\e[0m\e[48;5;045m\e[38;5;033m▄\e[0"
    echo -en "m\e[0m\e[48;5;045m\e[38;5;033m▄\e[0m\e[0m\e[48;5;045m\e"
    echo -en "[38;5;045m▄\e[0m\e[0m\e[48;5;255m\e[38;5;045m▄\e[0m\e[0"
    echo -en "m\e[48;5;255m\e[38;5;255m▄\e[0m\e[0m\e[48;5;231m\e[38;5"
    echo -en ";255m▄\e[0m\e[0m\e[48;5;231m\e[38;5;255m▄\e[0m\e[0m\e[4"
    echo -en "8;5;231m\e[38;5;231m▄\e[0m\e[0m\e[48;5;231m\e[38;5;231m"
    echo -en "▄\e[0m\e[0m\e[48;5;231m\e[38;5;255m▄\e[0m\e[0m\e[48;5;2"
    echo -en "31m\e[38;5;255m▄\e[0m\e[0m\e[48;5;231m\e[38;5;045m▄\e[0"
    echo -en "m\e[0m\e[48;5;231m\e[38;5;045m▄\e[0m\e[0m\e[48;5;255m\e"
    echo -en "[38;5;045m▄\e[0m\e[0m\e[48;5;255m\e[38;5;045m▄\e[0m\e[0"
    echo -en "m\e[7m\e[38;5;045m▄\e[0m\e[0m\e[48;5;045m\e[38;5;033m▄"
    echo -en "\e[0m\e[0m\e[48;5;045m\e[38;5;033m▄\e[0m\e[0m\e[48;5;04"
    echo -en "5m\e[38;5;033m▄\e[0m\e[0m\e[48;5;045m\e[38;5;033m▄\e[0m"
    echo -en "\e[0m\e[48;5;045m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e["
    echo -en "38;5;045m▄\e[0m\e[0m\e[48;5;045m\e[38;5;033m▄\e[0m\e[0m"
    echo -en "\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m"
    echo
    echo -en "              \e[48;5;232m\e[38;5;232m▄\e[0m\e[0m\e[48;"
    echo -en "5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄"
    echo -en "\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;03"
    echo -en "3m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m"
    echo -en "\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e["
    echo -en "38;5;232m▄\e[0m\e[0m\e[48;5;232m\e[38;5;232m▄\e[0m\e[0m"
    echo -en "\e[48;5;045m\e[38;5;232m▄\e[0m\e[0m\e[48;5;045m\e[38;5;"
    echo -en "232m▄\e[0m\e[0m\e[48;5;045m\e[38;5;232m▄\e[0m\e[0m\e[48"
    echo -en ";5;045m\e[38;5;232m▄\e[0m\e[0m\e[7m\e[38;5;232m▄\e[0m\e"
    echo -en "[0m        \e[7m\e[38;5;232m▄\e[0m\e[0m\e[7m\e[38;5;232"
    echo -en "m▄\e[0m\e[0m\e[7m\e[38;5;232m▄\e[0m\e[0m\e[7m\e[38;5;23"
    echo -en "2m▄\e[0m\e[0m\e[7m\e[38;5;232m▄\e[0m\e[0m\e[7m\e[38;5;2"
    echo -en "32m▄\e[0m\e[0m\e[7m\e[38;5;232m▄\e[0m\e[0m       \e[38;"
    echo -en "5;033m▄\e[0m\e[38;5;033m▄\e[0m\e[48;5;033m\e[38;5;033m▄"
    echo -en "\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;03"
    echo -en "3m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m"
    echo -en "\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e["
    echo -en "38;5;033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m"
    echo -en "\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;"
    echo -en "045m▄\e[0m\e[0m\e[48;5;045m\e[38;5;045m▄\e[0m\e[0m\e[48"
    echo -en ";5;045m\e[38;5;255m▄\e[0m\e[0m\e[48;5;045m\e[38;5;255m▄"
    echo -en "\e[0m\e[0m\e[48;5;255m\e[38;5;255m▄\e[0m\e[0m\e[48;5;25"
    echo -en "5m\e[38;5;255m▄\e[0m\e[0m\e[48;5;045m\e[38;5;255m▄\e[0m"
    echo -en "\e[0m\e[48;5;045m\e[38;5;045m▄\e[0m\e[0m\e[48;5;045m\e["
    echo -en "38;5;045m▄\e[0m\e[0m\e[48;5;045m\e[38;5;045m▄\e[0m\e[0m"
    echo -en "\e[38;5;045m▄\e[0m\e[38;5;033m▄\e[0m\e[38;5;033m▄\e[0m"
    echo -en "\e[38;5;033m▄\e[0m\e[38;5;045m▄\e[0m\e[38;5;033m▄\e[0m"
    echo -en "\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;"
    echo -en "033m▄\e[0m\e[0m\e[48;5;045m\e[38;5;033m▄\e[0m\e[0m\e[48"
    echo -en ";5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄"
    echo -en "\e[0m\e[0m"
    echo
    echo -en "               \e[7m\e[38;5;232m▄\e[0m\e[0m\e[7m\e[38;5"
    echo -en ";232m▄\e[0m\e[0m\e[48;5;033m\e[38;5;232m▄\e[0m\e[0m\e[4"
    echo -en "8;5;033m\e[38;5;232m▄\e[0m\e[0m\e[48;5;033m\e[38;5;232m"
    echo -en "▄\e[0m\e[0m\e[48;5;232m\e[38;5;033m▄\e[0m\e[0m\e[48;5;2"
    echo -en "32m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄\e[0"
    echo -en "m\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e"
    echo -en "[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0"
    echo -en "m\e[48;5;232m\e[38;5;232m▄\e[0m\e[0m\e[38;5;232m▄\e[0m "
    echo -en "                          \e[7m\e[38;5;033m▄\e[0m\e[0m"
    echo -en "\e[7m\e[38;5;033m▄\e[0m\e[0m\e[48;5;045m\e[38;5;033m▄\e"
    echo -en "[0m\e[0m\e[48;5;045m\e[38;5;033m▄\e[0m\e[0m\e[48;5;045m"
    echo -en "\e[38;5;033m▄\e[0m\e[0m\e[48;5;045m\e[38;5;033m▄\e[0m\e"
    echo -en "[0m\e[48;5;045m\e[38;5;045m▄\e[0m\e[0m\e[48;5;045m\e[38"
    echo -en ";5;045m▄\e[0m\e[0m\e[48;5;255m\e[38;5;045m▄\e[0m\e[0m\e"
    echo -en "[48;5;255m\e[38;5;045m▄\e[0m\e[0m\e[48;5;255m\e[38;5;25"
    echo -en "5m▄\e[0m\e[0m\e[48;5;255m\e[38;5;255m▄\e[0m\e[0m\e[48;5"
    echo -en ";255m\e[38;5;255m▄\e[0m\e[0m\e[48;5;045m\e[38;5;255m▄\e"
    echo -en "[0m\e[0m\e[48;5;045m\e[38;5;255m▄\e[0m\e[0m\e[48;5;045m"
    echo -en "\e[38;5;255m▄\e[0m\e[0m\e[48;5;045m\e[38;5;045m▄\e[0m\e"
    echo -en "[0m\e[48;5;045m\e[38;5;045m▄\e[0m\e[0m\e[48;5;045m\e[38"
    echo -en ";5;045m▄\e[0m\e[0m\e[7m\e[38;5;033m▄\e[0m\e[0m  \e[7m\e"
    echo -en "[38;5;033m▄\e[0m\e[0m\e[7m\e[38;5;033m▄\e[0m\e[0m\e[7m"
    echo -en "\e[38;5;033m▄\e[0m\e[0m"
    echo
    echo -en "               \e[38;5;232m▄\e[0m\e[48;5;232m\e[38;5;04"
    echo -en "5m▄\e[0m\e[0m\e[48;5;045m\e[38;5;045m▄\e[0m\e[0m\e[48;5"
    echo -en ";045m\e[38;5;045m▄\e[0m\e[0m\e[48;5;232m\e[38;5;045m▄\e"
    echo -en "[0m\e[0m\e[48;5;033m\e[38;5;232m▄\e[0m\e[0m\e[48;5;033m"
    echo -en "\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e"
    echo -en "[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e[38"
    echo -en ";5;232m▄\e[0m\e[0m\e[48;5;232m\e[38;5;045m▄\e[0m\e[0m\e"
    echo -en "[48;5;045m\e[38;5;045m▄\e[0m\e[0m\e[48;5;045m\e[38;5;04"
    echo -en "5m▄\e[0m\e[0m\e[48;5;232m\e[38;5;045m▄\e[0m\e[0m\e[38;5"
    echo -en ";232m▄\e[0m\e[38;5;232m▄\e[0m                          "
    echo -en " \e[38;5;033m▄\e[0m\e[38;5;033m▄\e[0m\e[48;5;033m\e[38;"
    echo -en "5;033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e["
    echo -en "48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;045m\e[38;5;033"
    echo -en "m▄\e[0m\e[0m\e[48;5;045m\e[38;5;045m▄\e[0m\e[0m\e[48;5;"
    echo -en "045m\e[38;5;045m▄\e[0m\e[0m\e[48;5;045m\e[38;5;045m▄\e["
    echo -en "0m\e[0m\e[48;5;255m\e[38;5;255m▄\e[0m\e[0m\e[48;5;255m"
    echo -en "\e[38;5;255m▄\e[0m\e[0m\e[48;5;255m\e[38;5;045m▄\e[0m\e"
    echo -en "[0m\e[48;5;045m\e[38;5;045m▄\e[0m\e[0m\e[48;5;045m\e[38"
    echo -en ";5;045m▄\e[0m\e[0m\e[48;5;045m\e[38;5;033m▄\e[0m\e[0m\e"
    echo -en "[48;5;033m\e[38;5;045m▄\e[0m\e[0m\e[48;5;045m\e[38;5;03"
    echo -en "3m▄\e[0m\e[0m"
    echo
    echo -en "            \e[38;5;232m▄\e[0m\e[48;5;232m\e[38;5;033m▄"
    echo -en "\e[0m\e[0m\e[48;5;232m\e[38;5;033m▄\e[0m\e[0m\e[48;5;04"
    echo -en "5m\e[38;5;232m▄\e[0m\e[0m\e[48;5;045m\e[38;5;045m▄\e[0m"
    echo -en "\e[0m\e[48;5;045m\e[38;5;045m▄\e[0m\e[0m\e[48;5;045m\e["
    echo -en "38;5;045m▄\e[0m\e[0m\e[48;5;045m\e[38;5;232m▄\e[0m\e[0m"
    echo -en "\e[7m\e[38;5;232m▄\e[0m\e[0m\e[7m\e[38;5;232m▄\e[0m\e[0"
    echo -en "m\e[7m\e[38;5;232m▄\e[0m\e[0m\e[7m\e[38;5;232m▄\e[0m\e["
    echo -en "0m\e[7m\e[38;5;232m▄\e[0m\e[0m\e[48;5;045m\e[38;5;232m▄"
    echo -en "\e[0m\e[0m\e[48;5;045m\e[38;5;045m▄\e[0m\e[0m\e[48;5;04"
    echo -en "5m\e[38;5;232m▄\e[0m\e[0m\e[48;5;232m\e[38;5;033m▄\e[0m"
    echo -en "\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e["
    echo -en "38;5;033m▄\e[0m\e[0m\e[48;5;232m\e[38;5;033m▄\e[0m\e[0m"
    echo -en "\e[38;5;232m▄\e[0m                       \e[7m\e[38;5;0"
    echo -en "33m▄\e[0m\e[0m\e[7m\e[38;5;033m▄\e[0m\e[0m\e[7m\e[38;5;"
    echo -en "033m▄\e[0m\e[0m\e[7m\e[38;5;033m▄\e[0m\e[0m\e[7m\e[38;5"
    echo -en ";033m▄\e[0m\e[0m\e[7m\e[38;5;033m▄\e[0m\e[0m\e[7m\e[38;"
    echo -en "5;033m▄\e[0m\e[0m\e[7m\e[38;5;033m▄\e[0m\e[0m\e[48;5;04"
    echo -en "5m\e[38;5;045m▄\e[0m\e[0m\e[48;5;045m\e[38;5;045m▄\e[0m"
    echo -en "\e[0m\e[48;5;255m\e[38;5;045m▄\e[0m\e[0m\e[48;5;045m\e["
    echo -en "38;5;045m▄\e[0m\e[0m\e[48;5;045m\e[38;5;045m▄\e[0m\e[0m"
    echo -en "\e[48;5;045m\e[38;5;045m▄\e[0m\e[0m\e[48;5;045m\e[38;5;"
    echo -en "045m▄\e[0m\e[0m\e[48;5;033m\e[38;5;045m▄\e[0m\e[0m\e[48"
    echo -en ";5;045m\e[38;5;033m▄\e[0m\e[0m\e[7m\e[38;5;033m▄\e[0m\e"
    echo -en "[0m"
    echo
    echo -en "          \e[38;5;232m▄\e[0m\e[48;5;232m\e[38;5;033m▄\e"
    echo -en "[0m\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m"
    echo -en "\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e"
    echo -en "[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;232m\e[38"
    echo -en ";5;033m▄\e[0m\e[0m\e[48;5;045m\e[38;5;232m▄\e[0m\e[0m\e"
    echo -en "[7m\e[38;5;232m▄\e[0m\e[0m     \e[38;5;232m▄\e[0m\e[48;"
    echo -en "5;232m\e[38;5;232m▄\e[0m\e[0m\e[48;5;232m\e[38;5;033m▄"
    echo -en "\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;03"
    echo -en "3m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m"
    echo -en "\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e["
    echo -en "38;5;033m▄\e[0m\e[0m\e[48;5;232m\e[38;5;232m▄\e[0m\e[0m"
    echo -en "                              \e[48;5;033m\e[38;5;045m▄"
    echo -en "\e[0m\e[0m\e[48;5;045m\e[38;5;045m▄\e[0m\e[0m\e[48;5;04"
    echo -en "5m\e[38;5;045m▄\e[0m\e[0m\e[7m\e[38;5;045m▄\e[0m\e[0m\e"
    echo -en "[7m\e[38;5;033m▄\e[0m\e[0m\e[48;5;045m\e[38;5;045m▄\e[0"
    echo -en "m\e[0m\e[48;5;045m\e[38;5;045m▄\e[0m\e[0m\e[48;5;045m\e"
    echo -en "[38;5;033m▄\e[0m\e[0m\e[7m\e[38;5;033m▄\e[0m\e[0m"
    echo
    echo -en "       \e[38;5;232m▄\e[0m\e[38;5;232m▄\e[0m\e[48;5;232m"
    echo -en "\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e"
    echo -en "[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e[38"
    echo -en ";5;033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e"
    echo -en "[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;03"
    echo -en "3m▄\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5"
    echo -en ";232m\e[38;5;232m▄\e[0m\e[0m     \e[38;5;232m▄\e[0m\e[4"
    echo -en "8;5;232m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;033m"
    echo -en "▄\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;0"
    echo -en "33m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄\e[0"
    echo -en "m\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e"
    echo -en "[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;232m▄\e[0m\e[0"
    echo -en "m\e[48;5;232m\e[38;5;232m▄\e[0m\e[0m                   "
    echo -en "          \e[48;5;033m\e[38;5;045m▄\e[0m\e[0m\e[7m\e[38"
    echo -en ";5;045m▄\e[0m\e[0m\e[7m\e[38;5;033m▄\e[0m\e[0m  \e[48;5"
    echo -en ";033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;045m\e[38;5;033m▄\e"
    echo -en "[0m\e[0m\e[7m\e[38;5;033m▄\e[0m\e[0m"
    echo
    echo -en "    \e[38;5;232m▄\e[0m\e[38;5;232m▄\e[0m\e[48;5;232m\e["
    echo -en "38;5;033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m"
    echo -en "\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;232m\e[38;5;"
    echo -en "033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;232m▄\e[0m\e[0m\e[48"
    echo -en ";5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄"
    echo -en "\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;03"
    echo -en "3m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m"
    echo -en "\e[0m\e[48;5;033m\e[38;5;232m▄\e[0m\e[0m\e[7m\e[38;5;23"
    echo -en "2m▄\e[0m\e[0m    \e[38;5;232m▄\e[0m\e[48;5;232m\e[38;5;"
    echo -en "033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48"
    echo -en ";5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄"
    echo -en "\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;03"
    echo -en "3m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;232m▄\e[0m"
    echo -en "\e[0m\e[48;5;232m\e[38;5;033m▄\e[0m\e[0m\e[48;5;232m\e["
    echo -en "38;5;033m▄\e[0m\e[0m\e[48;5;232m\e[38;5;033m▄\e[0m\e[0m"
    echo -en "\e[48;5;232m\e[38;5;033m▄\e[0m\e[0m\e[38;5;232m▄\e[0m  "
    echo -en "                        \e[7m\e[38;5;045m▄\e[0m\e[0m   "
    echo -en " \e[7m\e[38;5;033m▄\e[0m\e[0m"
    echo
    echo -en "  \e[38;5;232m▄\e[0m\e[48;5;232m\e[38;5;033m▄\e[0m\e[0m"
    echo -en "\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;"
    echo -en "033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48"
    echo -en ";5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄"
    echo -en "\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;03"
    echo -en "3m\e[38;5;033m▄\e[0m\e[0m\e[48;5;232m\e[38;5;033m▄\e[0m"
    echo -en "\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e["
    echo -en "38;5;033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m"
    echo -en "\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;232m\e[38;5;"
    echo -en "232m▄\e[0m\e[0m     \e[48;5;232m\e[38;5;232m▄\e[0m\e[0m"
    echo -en "\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;"
    echo -en "033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48"
    echo -en ";5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄"
    echo -en "\e[0m\e[0m\e[48;5;232m\e[38;5;033m▄\e[0m\e[0m\e[48;5;03"
    echo -en "3m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m"
    echo -en "\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e["
    echo -en "38;5;033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m"
    echo -en "\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;232m\e[38;5;"
    echo -en "033m▄\e[0m\e[0m\e[38;5;232m▄\e[0m"
    echo
    echo -en " \e[48;5;232m\e[38;5;232m▄\e[0m\e[0m\e[48;5;033m\e[38;5"
    echo -en ";232m▄\e[0m\e[0m\e[48;5;033m\e[38;5;232m▄\e[0m\e[0m\e[4"
    echo -en "8;5;033m\e[38;5;232m▄\e[0m\e[0m\e[48;5;033m\e[38;5;232m"
    echo -en "▄\e[0m\e[0m\e[48;5;033m\e[38;5;232m▄\e[0m\e[0m\e[48;5;0"
    echo -en "33m\e[38;5;232m▄\e[0m\e[0m\e[48;5;033m\e[38;5;232m▄\e[0"
    echo -en "m\e[0m\e[48;5;033m\e[38;5;232m▄\e[0m\e[0m\e[48;5;033m\e"
    echo -en "[38;5;232m▄\e[0m\e[0m\e[48;5;033m\e[38;5;232m▄\e[0m\e[0"
    echo -en "m\e[48;5;033m\e[38;5;232m▄\e[0m\e[0m\e[48;5;033m\e[38;5"
    echo -en ";232m▄\e[0m\e[0m\e[48;5;033m\e[38;5;232m▄\e[0m\e[0m\e[4"
    echo -en "8;5;232m\e[38;5;232m▄\e[0m\e[0m      \e[48;5;232m\e[38;"
    echo -en "5;232m▄\e[0m\e[0m\e[48;5;033m\e[38;5;232m▄\e[0m\e[0m\e["
    echo -en "48;5;033m\e[38;5;232m▄\e[0m\e[0m\e[48;5;033m\e[38;5;232"
    echo -en "m▄\e[0m\e[0m\e[48;5;033m\e[38;5;232m▄\e[0m\e[0m\e[48;5;"
    echo -en "033m\e[38;5;232m▄\e[0m\e[0m\e[48;5;033m\e[38;5;232m▄\e["
    echo -en "0m\e[0m\e[48;5;033m\e[38;5;232m▄\e[0m\e[0m\e[48;5;033m"
    echo -en "\e[38;5;232m▄\e[0m\e[0m\e[48;5;033m\e[38;5;232m▄\e[0m\e"
    echo -en "[0m\e[48;5;033m\e[38;5;232m▄\e[0m\e[0m\e[48;5;033m\e[38"
    echo -en ";5;232m▄\e[0m\e[0m\e[48;5;033m\e[38;5;232m▄\e[0m\e[0m\e"
    echo -en "[48;5;033m\e[38;5;232m▄\e[0m\e[0m\e[48;5;033m\e[38;5;23"
    echo -en "2m▄\e[0m\e[0m\e[48;5;232m\e[38;5;232m▄\e[0m\e[0m"
    echo
    echo
}

long_opt() {
    local arg shift="0"
    case "$1" in
        "--"*"="*) arg="${1#*=}"; [[ -n $arg ]] || usage 1 ;;
        *) shift="1"; shift; [[ $# -gt 0 ]] || usage 1; arg="$1" ;;
    esac
    echo "$arg"
    return $shift
}

read_resume_file() {
    host="$(json_get "host")"
    ignore=($(json_get "ignore[]"))
    simulate="$(json_get "simulate")"
    tls="$(json_get "tls")"
    wordlists=($(json_get "wordlists[]"))
}

subinfo() { echo -e "${color:+\e[36m}[=] $@\e[0m"; }

# summarize_results() {
#     [[ -n $summarize ]] || return
#     [[ -f $results ]] || return

#     info "Summarizing results"
#     while read -r result; do
#         good "${result:4}"
#     done < <(grep -Eos "\[\+\].+" $results | sort -u); unset result
# }

usage() {
    [[ $1 -ne 0 ]] || logo >&2
    echo "Usage: ${0##*/} [OPTIONS] <host/ip>[:port][/path][?query]"
    echo
    echo "Fuzz paths on a webserver. By default, MegaBuster will try"
    echo "to use the big.txt and common.txt lists from dirb and the"
    echo "directory-list-2.3-medium.txt list from DirBuster."
    echo
    echo "Options:"
    echo "    -a, --apend          Append user specified lists to"
    echo "                         the default"
    echo "    -c, --cache          Cache locations of defaults lists"
    echo "    -h, --help           Display this help message"
    echo "    -i, --ignore=CODE    Ignore specified return codes, can"
    echo "                         be used more than once, accepts"
    echo "                         csv"
    echo "    -l, --list=LIST      Use the specified wordlist (can be"
    echo "                         used more than once)"
    echo "    --nocolor            Disable colorized output"
    echo "    -p, --proxy=PROXY    Proxy traffic through PROXY"
    echo "    -r, --resume         Resume from a previous run"
    echo "    --simulate           Simulate output but do nothing"
    echo "    -t, --threads=NUM    Use the specied number of threads"
    echo "                         (default: $threads)"
    echo "    --timeout=SECS       Use specified timeout with curl"
    echo "                         (default: none)"
    echo "    --tls                Use TLS connection (https)"
    echo "    -v, --verbose        Do not hide parallel errors"
    echo
    exit $1
}

warn() { echo -e "${color:+\e[33m}[-] $@\e[0m"; }

write_resume_file() {
    cat >$json <<EOF
{
  "host": "${host:-${simulate:+simulation}}",
  "ignore": [
$(
    for i in $(seq 1 ${#ignore[@]}); do
        echo "    \"${ignore[$i - 1]}\"${ignore[$i]:+,}"
    done; unset i
)
  ],
  "simulate": "$simulate",
  "tls": "$tls",
  "wordlists": [
$(
    for i in $(seq 1 ${#wordlists[@]}); do
        echo "    \"${wordlists[$i - 1]}\"${wordlists[$i]:+,}"
    done; unset i
)
  ]
}
EOF
}

declare -a args ignore wordlists
unset append dlists help proxy recache resume simulate timeout tls
unset verbose
cache="${0##*/}.resume"
color="true"
curl="curl -IkLs"
dcache="$HOME/.cache/${0##*/}/default_list.locations"
joblog="$cache/joblog.txt"
json="$cache/${0##*/}.json"
threads="32"

# Parse command line options
while [[ $# -gt 0 ]]; do
    case "$1" in
        "--") shift && args+=("$@") && break ;;
        "-a"|"--append") append="true" ;;
        "-c"|"--cache") recache="true" ;;
        "-h"|"--help") help="true" ;;
        "-i"|"--ignore"*)
            arg="$(long_opt $@)" || shift
            ignore+=(${arg//,/ })
            ;;
        "-l"|"--list"*) wordlists+=($(long_opt $@)) || shift ;;
        "--nocolor") unset color ;;
        "-p"|"--proxy"*) proxy="--proxy $(long_opt $@)" || shift ;;
        "-r"|"--resume") resume="--resume" ;;
        "--simulate") simulate="true" ;;
        "-t"|"--threads"*) threads="$(long_opt $@)" || shift ;;
        "--timeout"*)
            arg="$(long_opt $@)" || shift
            timeout="--connect-timeout $arg --max-time $arg"
            ;;
        "--tls") tls="true" ;;
        "-v"|"--verbose") verbose="true" ;;
        *) args+=("$1") ;;
    esac
    shift
done
[[ -z ${args[@]} ]] || set -- "${args[@]}"

# Check for valid params and missing dependencies
[[ -z $help ]] || usage 0
[[ $# -eq 1 ]] || [[ -n $recache$resume$simulate ]] || usage 2
for dep in curl jq parallel; do
    [[ -n $(command -v $dep) ]] || errx 3 "$dep is not installed"
done; unset dep

# Cite if needed
if [[ ! -f $HOME/.parallel/will-cite ]]; then
    mkdir -p $HOME/.parallel
    parallel --citation
fi

# If defaults lists are not cached, find and cache
if [[ ! -f $dcache ]] || [[ -n $recache ]]; then
    cache_default_lists
    [[ -z $recache ]] || exit
fi

# Get default lists
while read -r wordlist; do
    dlists+=($wordlist)
done <$dcache; unset wordlist

# Use default lists if none provided or append was specified
if [[ ${#wordlists[@]} -eq 0 ]] || [[ -n $append ]]; then
    wordlists+=(${dlists[@]})
fi

# Ensure lists are provided and valid
[[ ${#wordlists[@]} -ne 0 ]] || errx 4 "No wordlists provided"
for wordlist in "${wordlists[@]}"; do
    [[ -f $wordlist ]] || errx 5 "Wordlist does not exist: $wordlist"
done; unset wordlist

# Save host
host="${1:-${simulate:+simulation}}"

# Ensure host is reachable
if [[ -z $simulate ]]; then
    ping -c 1 -W 1 ${host%%[:/]*} &>/dev/null
    [[ $? -eq 0 ]] || errx 6 "Target is out of range"
fi

# Ensure resume directory exists
mkdir -p $cache

# Check for resume file
if [[ -f $json ]] && [[ -z $resume ]]; then
    warn "Resume file found" >&2
    while :; do
        # Prompt whether to overwrite or resume
        read -n 1 -p "Would you like to resume [y/n/q]: " -s ans
        echo

        case "$ans" in
            "n") write_resume_file; break ;;
            "q") exit 0 ;;
            "y") read_resume_file; resume="--resume"; break ;;
            *) echo "Invalid response, try again!" ;;
        esac
    done
elif [[ -f $json ]]; then
    read_resume_file
elif [[ -n $resume ]]; then
    errx 7 "No resume file found in current directory"
else
    write_resume_file
fi

# Display logo
logo >&2

# Script used by parallel
script="/tmp/${0##*/}.parallel"

# Ensure cleanup on ^C
trap "clean -1" SIGINT

# Hide cursor
echo -en "\e[?25l"

info "MegaBuster is targeting $host"

# Process dataset
info "Processing wordlists for ammo"

total="0"
while read -r count; do
    ((total += count))
done < <(grep -cEhvs "^( *#.*)?$" "${wordlists[@]}"); unset count
[[ $total -gt 0 ]] || errx 8 "No ammo"

subinfo "$total shots to fire"

# Create sub-script
cat >$script <<EOF
#!/usr/bin/env bash

set -o noglob

check() {
    # Check GET and POST
    local data line type
    for type in GET POST; do
        case "\$type" in
            "POST") data="{}" ;;
            *) unset data ;;
        esac
        while read -r line; do
            case "\$line" in
                404) continue ;;
                ${ignore:+$(join_with "|" "${ignore[@]}")) continue ;;}
                5*) err "\$type /\$1 (\$line)" ;;
                4*) warn "\$type /\$1 (\$line)" ;;
                3*) subinfo "\$type /\$1 (\$line)" ;;
                *) good "\$type /\$1 (\$line)" ;;
            esac
        done < <(
            $curl \${data:+-d $data} $proxy $timeout -X \$type \\
            "http${tls:+s}://$host/\$1" | \\
            awk '/^(HTTP|Location)/ {print \$2}' | tr -d "\r" | \\
            sed -r "\\\$!N;s/\n/ /"
        ); unset line
    done; unset type
}

err() { echo -e "\r${color:+\e[31m}[!] \$@\e[0m\e[K"; }

errx() { echo -e "\r${color:+\e[31m}[!] \${@:2}\e[0m\e[K"; exit \$1; }

good() { echo -e "\r${color:+\e[32m}[+] \$@\e[0m\e[K"; }

info() { echo -e "\r${color:+\e[37m}[*] \$@\e[0m\e[K"; }

simulate() {
    local ret type
    case "\$((RANDOM % 2))" in
        0) type="GET" ;;
        *) type="POST" ;;
    esac
    case "\$((RANDOM % 6))" in
        0) ret="200" ;;
        1) ret="301" ;;
        2) ret="302" ;;
        3) ret="401" ;;
        4) ret="403" ;;
        *) ret="500" ;;
    esac
    case "\$((RANDOM % 64))" in
        8)
            case "\$ret" in
                404) return ;;
                ${ignore:+$(join_with "|" "${ignore[@]}")) return ;;}
                5*) err "\$type /\$1 (\$ret)" ;;
                4*) warn "\$type /\$1 (\$ret)" ;;
                3*) subinfo "\$type /\$1 (\$ret /some/other/path)" ;;
                *) good "\$type /\$1 (\$ret)" ;;
            esac
            ;;
    esac
}

subinfo() { echo -e "\r${color:+\e[36m}[=] \$@\e[0m\e[K"; }

warn() { echo -e "\r${color:+\e[33m}[-] \$@\e[0m\e[K"; }

# Ignore comments
comment_regex="^( *#.*)?$"
[[ ! "\$1" =~ \$comment_regex ]] || exit

# Remove leading slashes and trailing ^M
path="\${1#\${1%%[^/]*}}"
path="\${path%}"

# Fix any other ^M
path="\${path///\\\\\\\r}"

if [[ "x$simulate" != "x" ]]; then
    simulate "\$path"
else
    check "\$path"
fi
EOF
chmod 700 $script

cat ${wordlists[@]} | parallel --bar --joblog ${resume:++}$joblog \
    --lb -P $threads -r $resume $script {}
[[ -n $verbose ]] || echo -en "\e[1A\e[K" >&2

clean
