#!/usr/bin/env bash

clean() { rm -f $script; exit 0; }

err() { echo -en "\e[31m" >&2; echo -e "[!] $@\e[0m"; }

info() { echo -en "\e[37m" >&2; echo -e "[=] $@\e[0m"; }

logo() {
    echo >&2
    echo -en "                       \e[38;5;232m▄\e[0m\e[38;5;23" >&2
    echo -en "2m▄\e[0m\e[48;5;232m\e[38;5;045m▄\e[0m\e[0m\e[48;5;" >&2
    echo -en "232m\e[38;5;045m▄\e[0m\e[0m\e[48;5;232m\e[38;5;045m" >&2
    echo -en "▄\e[0m\e[0m\e[48;5;232m\e[38;5;045m▄\e[0m\e[0m\e[48" >&2
    echo -en ";5;232m\e[38;5;045m▄\e[0m\e[0m\e[38;5;232m▄\e[0m\e[" >&2
    echo -en "38;5;232m▄\e[0m" >&2
    echo >&2
    echo -en "                     \e[38;5;232m▄\e[0m\e[48;5;232m" >&2
    echo -en "\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄\e[" >&2
    echo -en "0m\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;0" >&2
    echo -en "33m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄" >&2
    echo -en "\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;" >&2
    echo -en "5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;045m\e[38;5;03" >&2
    echo -en "3m▄\e[0m\e[0m\e[48;5;045m\e[38;5;045m▄\e[0m\e[0m\e[" >&2
    echo -en "48;5;045m\e[38;5;045m▄\e[0m\e[0m\e[48;5;232m\e[38;5" >&2
    echo -en ";045m▄\e[0m\e[0m\e[38;5;232m▄\e[0m" >&2
    echo >&2
    echo -en "                    \e[38;5;232m▄\e[0m\e[48;5;232m" >&2
    echo -en "\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄\e[" >&2
    echo -en "0m\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;0" >&2
    echo -en "33m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄" >&2
    echo -en "\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;" >&2
    echo -en "5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;03" >&2
    echo -en "3m▄\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[" >&2
    echo -en "48;5;033m\e[38;5;045m▄\e[0m\e[0m\e[48;5;033m\e[38;5" >&2
    echo -en ";045m▄\e[0m\e[0m\e[48;5;033m\e[38;5;045m▄\e[0m\e[0m" >&2
    echo -en "\e[48;5;232m\e[38;5;033m▄\e[0m\e[0m\e[38;5;232m▄\e[" >&2
    echo -en "0m" >&2
    echo >&2
    echo -en "                    \e[48;5;232m\e[38;5;232m▄\e[0m" >&2
    echo -en "\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033" >&2
    echo -en "m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄\e" >&2
    echo -en "[0m\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;" >&2
    echo -en "033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;232m" >&2
    echo -en "▄\e[0m\e[0m\e[48;5;033m\e[38;5;232m▄\e[0m\e[0m\e[48" >&2
    echo -en ";5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;0" >&2
    echo -en "33m▄\e[0m\e[0m\e[48;5;045m\e[38;5;045m▄\e[0m\e[0m\e" >&2
    echo -en "[48;5;045m\e[38;5;045m▄\e[0m\e[0m\e[48;5;045m\e[38;" >&2
    echo -en "5;045m▄\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0" >&2
    echo -en "m\e[48;5;232m\e[38;5;232m▄\e[0m\e[0m" >&2
    echo >&2
    echo -en "                   \e[48;5;232m\e[38;5;232m▄\e[0m\e" >&2
    echo -en "[0m\e[48;5;045m\e[38;5;045m▄\e[0m\e[0m\e[48;5;045m" >&2
    echo -en "\e[38;5;196m▄\e[0m\e[0m\e[48;5;045m\e[38;5;045m▄\e[" >&2
    echo -en "0m\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;0" >&2
    echo -en "33m\e[38;5;232m▄\e[0m\e[0m\e[48;5;232m\e[38;5;223m▄" >&2
    echo -en "\e[0m\e[0m\e[48;5;223m\e[38;5;255m▄\e[0m\e[0m\e[48;" >&2
    echo -en "5;255m\e[38;5;255m▄\e[0m\e[0m\e[48;5;232m\e[38;5;23" >&2
    echo -en "2m▄\e[0m\e[0m\e[48;5;033m\e[38;5;232m▄\e[0m\e[0m\e[" >&2
    echo -en "48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e[38;5" >&2
    echo -en ";232m▄\e[0m\e[0m\e[48;5;232m\e[38;5;255m▄\e[0m\e[0m" >&2
    echo -en "\e[48;5;232m\e[38;5;232m▄\e[0m\e[0m\e[7m\e[38;5;232" >&2
    echo -en "m▄\e[0m\e[0m" >&2
    echo >&2
    echo -en "                  \e[38;5;232m▄\e[0m\e[48;5;232m\e[" >&2
    echo -en "38;5;232m▄\e[0m\e[0m\e[48;5;045m\e[38;5;045m▄\e[0m" >&2
    echo -en "\e[0m\e[48;5;196m\e[38;5;196m▄\e[0m\e[0m\e[48;5;045" >&2
    echo -en "m\e[38;5;045m▄\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄\e" >&2
    echo -en "[0m\e[0m\e[48;5;232m\e[38;5;232m▄\e[0m\e[0m\e[48;5;" >&2
    echo -en "223m\e[38;5;223m▄\e[0m\e[0m\e[48;5;255m\e[38;5;255m" >&2
    echo -en "▄\e[0m\e[0m\e[48;5;255m\e[38;5;255m▄\e[0m\e[0m\e[48" >&2
    echo -en ";5;232m\e[38;5;232m▄\e[0m\e[0m\e[48;5;255m\e[38;5;2" >&2
    echo -en "55m▄\e[0m\e[0m\e[48;5;232m\e[38;5;223m▄\e[0m\e[0m\e" >&2
    echo -en "[48;5;232m\e[38;5;232m▄\e[0m\e[0m\e[48;5;255m\e[38;" >&2
    echo -en "5;255m▄\e[0m\e[0m\e[48;5;232m\e[38;5;232m▄\e[0m\e[0" >&2
    echo -en "m" >&2
    echo >&2
    echo -en "               \e[38;5;232m▄\e[0m\e[48;5;232m\e[38;" >&2
    echo -en "5;045m▄\e[0m\e[0m\e[48;5;232m\e[38;5;045m▄\e[0m\e[0" >&2
    echo -en "m\e[48;5;045m\e[38;5;045m▄\e[0m\e[0m\e[48;5;045m\e[" >&2
    echo -en "38;5;045m▄\e[0m\e[0m\e[48;5;232m\e[38;5;045m▄\e[0m" >&2
    echo -en "\e[0m\e[48;5;045m\e[38;5;232m▄\e[0m\e[0m\e[48;5;045" >&2
    echo -en "m\e[38;5;232m▄\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄\e" >&2
    echo -en "[0m\e[0m\e[48;5;232m\e[38;5;232m▄\e[0m\e[0m\e[48;5;" >&2
    echo -en "223m\e[38;5;223m▄\e[0m\e[0m\e[48;5;223m\e[38;5;223m" >&2
    echo -en "▄\e[0m\e[0m\e[48;5;255m\e[38;5;232m▄\e[0m\e[0m\e[48" >&2
    echo -en ";5;255m\e[38;5;232m▄\e[0m\e[0m\e[48;5;255m\e[38;5;2" >&2
    echo -en "23m▄\e[0m\e[0m\e[48;5;223m\e[38;5;223m▄\e[0m\e[0m\e" >&2
    echo -en "[48;5;223m\e[38;5;223m▄\e[0m\e[0m\e[48;5;223m\e[38;" >&2
    echo -en "5;223m▄\e[0m\e[0m\e[48;5;232m\e[38;5;232m▄\e[0m\e[0" >&2
    echo -en "m \e[38;5;232m▄\e[0m\e[48;5;232m\e[38;5;033m▄\e[0m" >&2
    echo -en "\e[0m\e[48;5;232m\e[38;5;033m▄\e[0m\e[0m\e[48;5;232" >&2
    echo -en "m\e[38;5;033m▄\e[0m\e[0m\e[48;5;232m\e[38;5;033m▄\e" >&2
    echo -en "[0m\e[0m\e[48;5;232m\e[38;5;033m▄\e[0m\e[0m\e[48;5;" >&2
    echo -en "232m\e[38;5;033m▄\e[0m\e[0m\e[48;5;232m\e[38;5;232m" >&2
    echo -en "▄\e[0m\e[0m\e[38;5;232m▄\e[0m" >&2
    echo >&2
    echo -en "             \e[38;5;232m▄\e[0m\e[48;5;232m\e[38;5;" >&2
    echo -en "033m▄\e[0m\e[0m\e[48;5;232m\e[38;5;033m▄\e[0m\e[0m" >&2
    echo -en "\e[48;5;232m\e[38;5;033m▄\e[0m\e[0m\e[48;5;232m\e[3" >&2
    echo -en "8;5;033m▄\e[0m\e[0m\e[48;5;045m\e[38;5;232m▄\e[0m\e" >&2
    echo -en "[0m\e[48;5;045m\e[38;5;045m▄\e[0m\e[0m\e[48;5;045m" >&2
    echo -en "\e[38;5;045m▄\e[0m\e[0m\e[48;5;045m\e[38;5;045m▄\e[" >&2
    echo -en "0m\e[0m\e[48;5;232m\e[38;5;033m▄\e[0m\e[0m\e[48;5;2" >&2
    echo -en "32m\e[38;5;232m▄\e[0m\e[0m\e[48;5;033m\e[38;5;232m▄" >&2
    echo -en "\e[0m\e[0m\e[48;5;232m\e[38;5;033m▄\e[0m\e[0m\e[48;" >&2
    echo -en "5;223m\e[38;5;232m▄\e[0m\e[0m\e[48;5;223m\e[38;5;22" >&2
    echo -en "3m▄\e[0m\e[0m\e[48;5;223m\e[38;5;223m▄\e[0m\e[0m\e[" >&2
    echo -en "48;5;232m\e[38;5;223m▄\e[0m\e[0m\e[48;5;223m\e[38;5" >&2
    echo -en ";223m▄\e[0m\e[0m\e[48;5;223m\e[38;5;223m▄\e[0m\e[0m" >&2
    echo -en "\e[48;5;223m\e[38;5;232m▄\e[0m\e[0m\e[48;5;232m\e[3" >&2
    echo -en "8;5;045m▄\e[0m\e[0m\e[48;5;232m\e[38;5;232m▄\e[0m\e" >&2
    echo -en "[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m" >&2
    echo -en "\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄\e[" >&2
    echo -en "0m\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;0" >&2
    echo -en "33m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;232m▄" >&2
    echo -en "\e[0m\e[0m\e[48;5;232m\e[38;5;045m▄\e[0m\e[0m\e[48;" >&2
    echo -en "5;045m\e[38;5;196m▄\e[0m\e[0m\e[48;5;045m\e[38;5;23" >&2
    echo -en "2m▄\e[0m\e[0m\e[48;5;232m\e[38;5;045m▄\e[0m\e[0m\e[" >&2
    echo -en "38;5;232m▄\e[0m" >&2
    echo >&2
    echo -en "             \e[48;5;232m\e[38;5;232m▄\e[0m\e[0m\e[" >&2
    echo -en "48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e[38;5" >&2
    echo -en ";033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m" >&2
    echo -en "\e[48;5;033m\e[38;5;232m▄\e[0m\e[0m\e[48;5;232m\e[3" >&2
    echo -en "8;5;033m▄\e[0m\e[0m\e[48;5;232m\e[38;5;033m▄\e[0m\e" >&2
    echo -en "[0m\e[48;5;232m\e[38;5;033m▄\e[0m\e[0m\e[48;5;045m" >&2
    echo -en "\e[38;5;232m▄\e[0m\e[0m\e[48;5;045m\e[38;5;045m▄\e[" >&2
    echo -en "0m\e[0m\e[48;5;033m\e[38;5;045m▄\e[0m\e[0m\e[48;5;0" >&2
    echo -en "33m\e[38;5;033m▄\e[0m\e[0m\e[48;5;232m\e[38;5;033m▄" >&2
    echo -en "\e[0m\e[0m\e[48;5;232m\e[38;5;033m▄\e[0m\e[0m\e[48;" >&2
    echo -en "5;232m\e[38;5;033m▄\e[0m\e[0m\e[48;5;232m\e[38;5;04" >&2
    echo -en "5m▄\e[0m\e[0m\e[48;5;232m\e[38;5;045m▄\e[0m\e[0m\e[" >&2
    echo -en "48;5;232m\e[38;5;045m▄\e[0m\e[0m\e[48;5;232m\e[38;5" >&2
    echo -en ";045m▄\e[0m\e[0m\e[48;5;045m\e[38;5;045m▄\e[0m\e[0m" >&2
    echo -en "\e[48;5;045m\e[38;5;045m▄\e[0m\e[0m\e[48;5;232m\e[3" >&2
    echo -en "8;5;232m▄\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e" >&2
    echo -en "[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m" >&2
    echo -en "\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄\e[" >&2
    echo -en "0m\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;2" >&2
    echo -en "32m\e[38;5;232m▄\e[0m\e[0m\e[48;5;045m\e[38;5;045m▄" >&2
    echo -en "\e[0m\e[0m\e[48;5;196m\e[38;5;196m▄\e[0m\e[0m\e[48;" >&2
    echo -en "5;232m\e[38;5;232m▄\e[0m\e[0m\e[48;5;045m\e[38;5;04" >&2
    echo -en "5m▄\e[0m\e[0m\e[48;5;232m\e[38;5;232m▄\e[0m\e[0m" >&2
    echo >&2
    echo -en "             \e[48;5;232m\e[38;5;232m▄\e[0m\e[0m\e[" >&2
    echo -en "48;5;033m\e[38;5;232m▄\e[0m\e[0m\e[48;5;033m\e[38;5" >&2
    echo -en ";232m▄\e[0m\e[0m\e[48;5;232m\e[38;5;033m▄\e[0m\e[0m" >&2
    echo -en "\e[48;5;232m\e[38;5;232m▄\e[0m\e[0m\e[48;5;033m\e[3" >&2
    echo -en "8;5;232m▄\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e" >&2
    echo -en "[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m" >&2
    echo -en "\e[38;5;033m▄\e[0m\e[0m\e[48;5;232m\e[38;5;232m▄\e[" >&2
    echo -en "0m\e[0m\e[48;5;045m\e[38;5;045m▄\e[0m\e[0m\e[48;5;0" >&2
    echo -en "45m\e[38;5;045m▄\e[0m\e[0m\e[48;5;045m\e[38;5;045m▄" >&2
    echo -en "\e[0m\e[0m\e[48;5;045m\e[38;5;045m▄\e[0m\e[0m\e[48;" >&2
    echo -en "5;045m\e[38;5;045m▄\e[0m\e[0m\e[48;5;045m\e[38;5;23" >&2
    echo -en "2m▄\e[0m\e[0m\e[7m\e[38;5;232m▄\e[0m\e[0m\e[7m\e[38" >&2
    echo -en ";5;232m▄\e[0m\e[0m\e[7m\e[38;5;232m▄\e[0m\e[0m\e[7m" >&2
    echo -en "\e[38;5;232m▄\e[0m\e[0m\e[7m\e[38;5;232m▄\e[0m\e[0m" >&2
    echo -en "\e[7m\e[38;5;232m▄\e[0m\e[0m\e[48;5;033m\e[38;5;232" >&2
    echo -en "m▄\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[4" >&2
    echo -en "8;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;" >&2
    echo -en "033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m" >&2
    echo -en "\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;232m\e[3" >&2
    echo -en "8;5;033m▄\e[0m\e[0m\e[48;5;045m\e[38;5;232m▄\e[0m\e" >&2
    echo -en "[0m\e[48;5;045m\e[38;5;232m▄\e[0m\e[0m\e[7m\e[38;5;" >&2
    echo -en "232m▄\e[0m\e[0m" >&2
    echo >&2
    echo -en "              \e[48;5;232m\e[38;5;232m▄\e[0m\e[0m\e" >&2
    echo -en "[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e[38;" >&2
    echo -en "5;033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0" >&2
    echo -en "m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e[" >&2
    echo -en "38;5;033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m" >&2
    echo -en "\e[0m\e[48;5;033m\e[38;5;232m▄\e[0m\e[0m\e[48;5;232" >&2
    echo -en "m\e[38;5;232m▄\e[0m\e[0m\e[48;5;045m\e[38;5;232m▄\e" >&2
    echo -en "[0m\e[0m\e[48;5;045m\e[38;5;232m▄\e[0m\e[0m\e[48;5;" >&2
    echo -en "045m\e[38;5;232m▄\e[0m\e[0m\e[48;5;045m\e[38;5;232m" >&2
    echo -en "▄\e[0m\e[0m\e[7m\e[38;5;232m▄\e[0m\e[0m        \e[7" >&2
    echo -en "m\e[38;5;232m▄\e[0m\e[0m\e[7m\e[38;5;232m▄\e[0m\e[0" >&2
    echo -en "m\e[7m\e[38;5;232m▄\e[0m\e[0m\e[7m\e[38;5;232m▄\e[0" >&2
    echo -en "m\e[0m\e[7m\e[38;5;232m▄\e[0m\e[0m\e[7m\e[38;5;232m" >&2
    echo -en "▄\e[0m\e[0m\e[7m\e[38;5;232m▄\e[0m\e[0m" >&2
    echo >&2
    echo -en "               \e[7m\e[38;5;232m▄\e[0m\e[0m\e[7m\e[" >&2
    echo -en "38;5;232m▄\e[0m\e[0m\e[48;5;033m\e[38;5;232m▄\e[0m" >&2
    echo -en "\e[0m\e[48;5;033m\e[38;5;232m▄\e[0m\e[0m\e[48;5;033" >&2
    echo -en "m\e[38;5;232m▄\e[0m\e[0m\e[48;5;232m\e[38;5;033m▄\e" >&2
    echo -en "[0m\e[0m\e[48;5;232m\e[38;5;033m▄\e[0m\e[0m\e[48;5;" >&2
    echo -en "033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;033m" >&2
    echo -en "▄\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48" >&2
    echo -en ";5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;232m\e[38;5;2" >&2
    echo -en "32m▄\e[0m\e[0m\e[38;5;232m▄\e[0m" >&2
    echo >&2
    echo -en "               \e[38;5;232m▄\e[0m\e[48;5;232m\e[38;" >&2
    echo -en "5;045m▄\e[0m\e[0m\e[48;5;045m\e[38;5;045m▄\e[0m\e[0" >&2
    echo -en "m\e[48;5;045m\e[38;5;045m▄\e[0m\e[0m\e[48;5;232m\e[" >&2
    echo -en "38;5;045m▄\e[0m\e[0m\e[48;5;033m\e[38;5;232m▄\e[0m" >&2
    echo -en "\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033" >&2
    echo -en "m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄\e" >&2
    echo -en "[0m\e[0m\e[48;5;033m\e[38;5;232m▄\e[0m\e[0m\e[48;5;" >&2
    echo -en "232m\e[38;5;045m▄\e[0m\e[0m\e[48;5;045m\e[38;5;045m" >&2
    echo -en "▄\e[0m\e[0m\e[48;5;045m\e[38;5;045m▄\e[0m\e[0m\e[48" >&2
    echo -en ";5;232m\e[38;5;045m▄\e[0m\e[0m\e[38;5;232m▄\e[0m\e[" >&2
    echo -en "38;5;232m▄\e[0m" >&2
    echo >&2
    echo -en "            \e[38;5;232m▄\e[0m\e[48;5;232m\e[38;5;0" >&2
    echo -en "33m▄\e[0m\e[0m\e[48;5;232m\e[38;5;033m▄\e[0m\e[0m\e" >&2
    echo -en "[48;5;045m\e[38;5;232m▄\e[0m\e[0m\e[48;5;045m\e[38;" >&2
    echo -en "5;045m▄\e[0m\e[0m\e[48;5;045m\e[38;5;045m▄\e[0m\e[0" >&2
    echo -en "m\e[48;5;045m\e[38;5;045m▄\e[0m\e[0m\e[48;5;045m\e[" >&2
    echo -en "38;5;232m▄\e[0m\e[0m\e[7m\e[38;5;232m▄\e[0m\e[0m\e[" >&2
    echo -en "7m\e[38;5;232m▄\e[0m\e[0m\e[7m\e[38;5;232m▄\e[0m\e[" >&2
    echo -en "0m\e[7m\e[38;5;232m▄\e[0m\e[0m\e[7m\e[38;5;232m▄\e[" >&2
    echo -en "0m\e[0m\e[48;5;045m\e[38;5;232m▄\e[0m\e[0m\e[48;5;0" >&2
    echo -en "45m\e[38;5;045m▄\e[0m\e[0m\e[48;5;045m\e[38;5;232m▄" >&2
    echo -en "\e[0m\e[0m\e[48;5;232m\e[38;5;033m▄\e[0m\e[0m\e[48;" >&2
    echo -en "5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;03" >&2
    echo -en "3m▄\e[0m\e[0m\e[48;5;232m\e[38;5;033m▄\e[0m\e[0m\e[" >&2
    echo -en "38;5;232m▄\e[0m" >&2
    echo >&2
    echo -en "          \e[38;5;232m▄\e[0m\e[48;5;232m\e[38;5;033" >&2
    echo -en "m▄\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[4" >&2
    echo -en "8;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;" >&2
    echo -en "033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m" >&2
    echo -en "\e[48;5;232m\e[38;5;033m▄\e[0m\e[0m\e[48;5;045m\e[3" >&2
    echo -en "8;5;232m▄\e[0m\e[0m\e[7m\e[38;5;232m▄\e[0m\e[0m    " >&2
    echo -en " \e[38;5;232m▄\e[0m\e[48;5;232m\e[38;5;232m▄\e[0m\e" >&2
    echo -en "[0m\e[48;5;232m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m" >&2
    echo -en "\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄\e[" >&2
    echo -en "0m\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;0" >&2
    echo -en "33m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄" >&2
    echo -en "\e[0m\e[0m\e[48;5;232m\e[38;5;232m▄\e[0m\e[0m" >&2
    echo >&2
    echo -en "       \e[38;5;232m▄\e[0m\e[38;5;232m▄\e[0m\e[48;5;" >&2
    echo -en "232m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;033m" >&2
    echo -en "▄\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48" >&2
    echo -en ";5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;0" >&2
    echo -en "33m▄\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e" >&2
    echo -en "[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e[38;" >&2
    echo -en "5;033m▄\e[0m\e[0m\e[48;5;232m\e[38;5;232m▄\e[0m\e[0" >&2
    echo -en "m     \e[38;5;232m▄\e[0m\e[48;5;232m\e[38;5;033m▄\e" >&2
    echo -en "[0m\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;" >&2
    echo -en "033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;033m" >&2
    echo -en "▄\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48" >&2
    echo -en ";5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;0" >&2
    echo -en "33m▄\e[0m\e[0m\e[48;5;033m\e[38;5;232m▄\e[0m\e[0m\e" >&2
    echo -en "[48;5;232m\e[38;5;232m▄\e[0m\e[0m" >&2
    echo >&2
    echo -en "    \e[38;5;232m▄\e[0m\e[38;5;232m▄\e[0m\e[48;5;232" >&2
    echo -en "m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄\e" >&2
    echo -en "[0m\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;" >&2
    echo -en "232m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;232m" >&2
    echo -en "▄\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48" >&2
    echo -en ";5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;0" >&2
    echo -en "33m▄\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e" >&2
    echo -en "[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e[38;" >&2
    echo -en "5;232m▄\e[0m\e[0m\e[7m\e[38;5;232m▄\e[0m\e[0m    \e" >&2
    echo -en "[38;5;232m▄\e[0m\e[48;5;232m\e[38;5;033m▄\e[0m\e[0m" >&2
    echo -en "\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e[3" >&2
    echo -en "8;5;033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e" >&2
    echo -en "[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m" >&2
    echo -en "\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;232m▄\e[" >&2
    echo -en "0m\e[0m\e[48;5;232m\e[38;5;033m▄\e[0m\e[0m\e[48;5;2" >&2
    echo -en "32m\e[38;5;033m▄\e[0m\e[0m\e[48;5;232m\e[38;5;033m▄" >&2
    echo -en "\e[0m\e[0m\e[48;5;232m\e[38;5;033m▄\e[0m\e[0m\e[38;" >&2
    echo -en "5;232m▄\e[0m" >&2
    echo >&2
    echo -en "  \e[38;5;232m▄\e[0m\e[48;5;232m\e[38;5;033m▄\e[0m" >&2
    echo -en "\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033" >&2
    echo -en "m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄\e" >&2
    echo -en "[0m\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;" >&2
    echo -en "033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;033m" >&2
    echo -en "▄\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48" >&2
    echo -en ";5;232m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;0" >&2
    echo -en "33m▄\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e" >&2
    echo -en "[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e[38;" >&2
    echo -en "5;033m▄\e[0m\e[0m\e[48;5;232m\e[38;5;232m▄\e[0m\e[0" >&2
    echo -en "m     \e[48;5;232m\e[38;5;232m▄\e[0m\e[0m\e[48;5;03" >&2
    echo -en "3m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄" >&2
    echo -en "\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;" >&2
    echo -en "5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;03" >&2
    echo -en "3m▄\e[0m\e[0m\e[48;5;232m\e[38;5;033m▄\e[0m\e[0m\e[" >&2
    echo -en "48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e[38;5" >&2
    echo -en ";033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m" >&2
    echo -en "\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e[3" >&2
    echo -en "8;5;033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e" >&2
    echo -en "[0m\e[48;5;232m\e[38;5;033m▄\e[0m\e[0m\e[38;5;232m▄" >&2
    echo -en "\e[0m" >&2
    echo >&2
    echo -en " \e[48;5;232m\e[38;5;232m▄\e[0m\e[0m\e[48;5;033m\e[" >&2
    echo -en "38;5;232m▄\e[0m\e[0m\e[48;5;033m\e[38;5;232m▄\e[0m" >&2
    echo -en "\e[0m\e[48;5;033m\e[38;5;232m▄\e[0m\e[0m\e[48;5;033" >&2
    echo -en "m\e[38;5;232m▄\e[0m\e[0m\e[48;5;033m\e[38;5;232m▄\e" >&2
    echo -en "[0m\e[0m\e[48;5;033m\e[38;5;232m▄\e[0m\e[0m\e[48;5;" >&2
    echo -en "033m\e[38;5;232m▄\e[0m\e[0m\e[48;5;033m\e[38;5;232m" >&2
    echo -en "▄\e[0m\e[0m\e[48;5;033m\e[38;5;232m▄\e[0m\e[0m\e[48" >&2
    echo -en ";5;033m\e[38;5;232m▄\e[0m\e[0m\e[48;5;033m\e[38;5;2" >&2
    echo -en "32m▄\e[0m\e[0m\e[48;5;033m\e[38;5;232m▄\e[0m\e[0m\e" >&2
    echo -en "[48;5;033m\e[38;5;232m▄\e[0m\e[0m\e[48;5;232m\e[38;" >&2
    echo -en "5;232m▄\e[0m\e[0m      \e[48;5;232m\e[38;5;232m▄\e[" >&2
    echo -en "0m\e[0m\e[48;5;033m\e[38;5;232m▄\e[0m\e[0m\e[48;5;0" >&2
    echo -en "33m\e[38;5;232m▄\e[0m\e[0m\e[48;5;033m\e[38;5;232m▄" >&2
    echo -en "\e[0m\e[0m\e[48;5;033m\e[38;5;232m▄\e[0m\e[0m\e[48;" >&2
    echo -en "5;033m\e[38;5;232m▄\e[0m\e[0m\e[48;5;033m\e[38;5;23" >&2
    echo -en "2m▄\e[0m\e[0m\e[48;5;033m\e[38;5;232m▄\e[0m\e[0m\e[" >&2
    echo -en "48;5;033m\e[38;5;232m▄\e[0m\e[0m\e[48;5;033m\e[38;5" >&2
    echo -en ";232m▄\e[0m\e[0m\e[48;5;033m\e[38;5;232m▄\e[0m\e[0m" >&2
    echo -en "\e[48;5;033m\e[38;5;232m▄\e[0m\e[0m\e[48;5;033m\e[3" >&2
    echo -en "8;5;232m▄\e[0m\e[0m\e[48;5;033m\e[38;5;232m▄\e[0m\e" >&2
    echo -en "[0m\e[48;5;033m\e[38;5;232m▄\e[0m\e[0m\e[48;5;232m" >&2
    echo -e "\e[38;5;232m▄\e[0m\e[0m" >&2
    echo >&2
}

usage() {
    [[ $1 -ne 0 ]] || logo
    echo "Usage: ${0/*\//} [OPTIONS] <host/ip>"
    echo
    echo "Simple bash version of DirBuster or dirb"
    echo
    echo "Options:"
    echo "    -h, --help           Display this help message"
    echo "    -l, --list=LIST      Use the specified wordlist"
    echo "                         (default: $list"
    echo "                         from $dirbuster)"
    echo "    -p, --parallel       Run using parallel"
    local default="(default: $threads)"
    echo "    -t, --threads=NUM    Use the specied number of threads"
    echo "                         if running in parallel $default"
    echo "    --test               Temporary for testing"
    echo
    exit $1
}

warn() { echo -en "\e[33m" >&2; echo -e "[-] $@\e[0m"; }

declare -a args
unset parallel test wordlist
list="directory-list-2.3-medium.txt"
dirbuster="$(
    find -O3 /usr -name "dirbuster" -type d -print -quit 2>/dev/null
)"
threads="32"

if [[ -n $dirbuster ]]; then
    wordlist="$(
        find $dirbuster -name "$list" -type f -print -quit 2>/dev/null
    )"
fi

while [[ $# -gt 0 ]]; do
    case "$1" in
        "--") shift && args+=("$@") && break ;;
        "-h"|"--help") usage 0 ;;
        "-l"|"--list"*)
            case "$1" in
                "--"*"="*) arg="${1#*=}"; [[ -n $arg ]] || usage 1 ;;
                *) shift; [[ $# -gt 0 ]] || usage 1; arg="$1" ;;
            esac
            wordlist="$arg"
            ;;
        "-p"|"--parallel") parallel="true" ;;
        "-t"|"--threads"*)
            case "$1" in
                "--"*"="*) arg="${1#*=}"; [[ -n $arg ]] || usage 1 ;;
                *) shift; [[ $# -gt 0 ]] || usage 1; arg="$1" ;;
            esac
            threads="$arg"
            ;;
        "--test") test="true" ;;
        *) args+=("$1") ;;
    esac
    shift
done
[[ -z ${args[@]} ]] || set -- "${args[@]}"

[[ $# -eq 1 ]] || usage 2
if [[ ! -f $wordlist ]]; then
    echo "Wordlist does not exist"
    exit 3
fi

logo

if [[ -n $parallel ]] && [[ -z $(command -v parallel) ]]; then
    warn "Parallel is not installed, using default behavior"
    unset parallel
fi

script="/tmp/${0/*\//}"
trap clean SIGINT

cat >$script <<EOF
#!/usr/bin/env bash
#err() { echo -e "\\r\\e[31m[!] \$@\\e[0m$(tput el)"; }
info() { echo -e "\\r\\e[32m[+] \$@\\e[0m$(tput el)"; }
#warn() { echo -e "\\r\\e[33m[-] \$@\\e[0m$(tput el)"; }
if [[ x"$test" != "x" ]]; then
    let "rand = RANDOM % 50"
    [[ \$rand -ne 7 ]] || info "\$1"
    let "rand = RANDOM % 50"
    [[ \$rand -ne 7 ]] || info "\$1/"
else
    data="\$(
        curl -Iks "http://$1/\$1" | \
        awk '/^(HTTP\/1|Content-Length)/ {print \$2}'
    )"
    if [[ -n \$data ]] &&
       [[ \$(echo "\$data" | head -n 1) -ne 404 ]]
    then
        info "\$1 (\$data)"
    fi
fi
EOF
chmod 700 $script

declare -a dataset=($(cat $wordlist | grep -Ev "^( *#.*)?$"))
if [[ -z ${dataset[@]} ]]; then
    err "No dataset provided"
    exit 4
fi
let "total = ${#dataset[@]}"

if [[ $total -gt 0 ]]; then
    if [[ -n $parallel ]]; then
        # Math
        left="$total"
        marker="0"
        maxdata="$(
            parallel -r --show-limit </dev/null | \
            awk '/Maximal used/ {print $NF; exit}'
        )"
        [[ $maxdata -lt 5000 ]] || let "maxdata -= 5000"
        let "remainder = total % maxdata"
        round="0"
        let "rounds = total / maxdata"
        [[ $remainder -eq 0 ]] || let "rounds += 1"

        # Loop thru rounds
        info "$total jobs to run"
        [[ $rounds -eq 1 ]] || info "Splitting into $rounds rounds"
        while [[ $left -gt 0 ]]; do
            let "round += 1"
            [[ $rounds -eq 1 ]] || warn "Round $round"

            increment="$left"
            [[ $left -lt $maxdata ]] || let "increment = $maxdata - 1"

            parallel --bar --lb -P $threads -r $script {} ::: \
                ${dataset[@]:$marker:$increment}

            let "left -= increment"
            let "marker += increment"
        done
    else
        let "count = 1"
        clear="$(tput el)"
        for data in "${dataset[@]}"; do
            echo -en "\r[$count/$total]$clear" >&2
            $script "$data"
            let "count += 1"
        done; unset data
    fi
fi

clean
