#!/usr/bin/env bash
# A script to fuzz paths on a webserver.
# by Miles Whittaker <mjwhitta@gmail.com>
#
# --------------------------------------------------------------------
# The MIT License (MIT)
#
# Copyright (c) 2018 Miles Whittaker
#
# Permission is hereby granted, free of charge, to any person
# obtaining a copy of this software and associated documentation files
# (the "Software"), to deal in the Software without restriction,
# including without limitation the rights to use, copy, modify, merge,
# publish, distribute, sublicense, and/or sell copies of the Software,
# and to permit persons to whom the Software is furnished to do so,
# subject to the following conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
# BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
# ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
# --------------------------------------------------------------------

### Helpers begin
set -o noglob
trap "clean 128" SIGINT # Ensure cleanup on ^C
check_deps() {
    for d in "${deps[@]}"; do
        [[ -n $(command -v "$d") ]] || errx 127 "$d is not installed"
    done; unset d
}
check_lock() {
    [[ -n $cache ]] || errx 126 "Cache is not defined"
    mkdir -p "$cache"
    if [[ -f "$cache.lock" ]]; then
        errx 125 "$cache.lock already exists"
    fi
    echo "$$" >"$cache.lock"
}
check_resume_file() {
    if [[ -f "$json" ]] && [[ -z $resume ]]; then
        warn "Resume file found" >&2
        while :; do
            # Prompt whether to overwrite or resume
            local a
            read -n 1 -p "Would you like to resume [y/n/q/c]: " -rs a
            echo

            case "$a" in
                "c") clean 0 ;;
                "n") write_resume_file; break ;;
                "q") exit 0 ;;
                "y") read_resume_file; resume="--resume"; break ;;
                *) echo "Invalid response, try again!" ;;
            esac
        done
    elif [[ -f "$json" ]]; then
        read_resume_file
    elif [[ -n $resume ]]; then
        errx 124 "No resume file found"
    else
        write_resume_file
    fi
}
clean() {
    if [[ ${1:-0} -eq 0 ]]; then
        [[ -z $cache ]] || [[ ! -d "$cache" ]] || rm -rf "$cache"
    fi
    [[ -z $script ]] || [[ ! -f "$script" ]] || rm -f "$script"
    [[ ${1:-0} -eq 125 ]] || [[ -z $cache ]] || rm -f "$cache.lock"
    show_cursor
    exit "${1:-0}"
}
err() { echo -e "${color:+\e[31m}[!] $*\e[0m"; }
errx() { echo -e "${color:+\e[31m}[!] ${*:2}\e[0m"; clean "$1"; }
good() { echo -e "${color:+\e[32m}[+] $*\e[0m"; }
hide_cursor() { echo -en "\e[?25l"; }
info() { echo -e "${color:+\e[37m}[*] $*\e[0m"; }
json_get() {
    if [[ -z $json ]] || [[ ! -f "$json" ]]; then
        return
    fi
    jq -cr ".$*" "$json" | sed -r "s/^null$//g"
}
long_opt() {
    local arg shift="0"
    case "$1" in
        "--"*"="*) arg="${1#*=}"; [[ -n $arg ]] || usage 123 ;;
        *) shift="1"; shift; [[ $# -gt 0 ]] || usage 123; arg="$1" ;;
    esac
    echo "$arg"
    return $shift
}
show_cursor() { echo -en "\e[?25h"; }
subinfo() { echo -e "${color:+\e[36m}[=] $*\e[0m"; }
warn() { echo -e "${color:+\e[33m}[-] $*\e[0m"; }
### Helpers end

cache_default_lists() {
    # Create dcache directory
    mkdir -p "$(dirname "$dcache")"
    rm -f "$dcache"

    local dirb_blist="big.txt"
    local dirb_clist="common.txt"
    local dirbuster_list="directory-list-2.3-medium.txt"
    local list wordlist

    # Find dirb directory
    local dirb="$(
        find -O3 /usr -maxdepth 4 -name "dirb" -type d -print -quit \
        2>/dev/null
    )"

    # If dirb was found, find the lists
    if [[ -n $dirb ]]; then
        for list in $dirb_blist $dirb_clist; do
            wordlist="$(
                find "$dirb" -name "$list" -type f -print -quit \
                2>/dev/null
            )"

            # Cache location of list
            [[ -z $wordlist ]] || echo "$wordlist" >>"$dcache"
        done; unset list
    fi

    # Find dirbuster directory
    local dirbuster="$(
        find -O3 /usr -maxdepth 4 -name "dirbuster" -type d -print \
        -quit 2>/dev/null
    )"

    # If dirbuster was found, find the list
    if [[ -n $dirbuster ]]; then
        wordlist="$(
            find "$dirbuster" -name "$dirbuster_list" -type f -print \
            -quit 2>/dev/null
        )"

        # Cache location of list
        [[ -z $wordlist ]] || echo "$wordlist" >>"$dcache"
    fi

    touch "$dcache"
}

join_with() { local IFS="$1"; echo "${*:2}"; }

logo() {
    [[ -n $color ]] || return
    [[ -n $(command -v tput) ]] || return
    [[ $(tput cols) -ge 81 ]] || return
    echo
    echo -en "                       \e[38;5;232m▄\e[0m\e[38;5;232m▄"
    echo -en "\e[0m\e[48;5;232m\e[38;5;045m▄\e[0m\e[0m\e[48;5;232m\e["
    echo -en "38;5;045m▄\e[0m\e[0m\e[48;5;232m\e[38;5;045m▄\e[0m\e[0m"
    echo -en "\e[48;5;232m\e[38;5;045m▄\e[0m\e[0m\e[48;5;232m\e[38;5;"
    echo -en "045m▄\e[0m\e[0m\e[38;5;232m▄\e[0m\e[38;5;232m▄\e[0m    "
    echo -en "                         \e[7m\e[38;5;045m▄\e[0m\e[0m\e"
    echo -en "[38;5;045m▄\e[0m   \e[7m\e[38;5;033m▄\e[0m\e[0m\e[38;5;"
    echo -en "033m▄\e[0m\e[38;5;033m▄\e[0m"
    echo
    echo -en "                     \e[38;5;232m▄\e[0m\e[48;5;232m\e[3"
    echo -en "8;5;033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m"
    echo -en "\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;"
    echo -en "033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48"
    echo -en ";5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄"
    echo -en "\e[0m\e[0m\e[48;5;045m\e[38;5;033m▄\e[0m\e[0m\e[48;5;04"
    echo -en "5m\e[38;5;045m▄\e[0m\e[0m\e[48;5;045m\e[38;5;045m▄\e[0m"
    echo -en "\e[0m\e[48;5;232m\e[38;5;045m▄\e[0m\e[0m\e[38;5;232m▄\e"
    echo -en "[0m                            \e[7m\e[38;5;033m▄\e[0m"
    echo -en "\e[0m\e[48;5;045m\e[38;5;045m▄\e[0m\e[0m\e[48;5;033m\e["
    echo -en "38;5;045m▄\e[0m\e[0m\e[38;5;045m▄\e[0m \e[7m\e[38;5;033"
    echo -en "m▄\e[0m\e[0m\e[48;5;045m\e[38;5;045m▄\e[0m\e[0m\e[48;5;"
    echo -en "033m\e[38;5;045m▄\e[0m\e[0m\e[38;5;033m▄\e[0m"
    echo
    echo -en "                    \e[38;5;232m▄\e[0m\e[48;5;232m\e[38"
    echo -en ";5;033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e"
    echo -en "[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;03"
    echo -en "3m▄\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5"
    echo -en ";033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄\e"
    echo -en "[0m\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m"
    echo -en "\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;045m▄\e[0m\e"
    echo -en "[0m\e[48;5;033m\e[38;5;045m▄\e[0m\e[0m\e[48;5;033m\e[38"
    echo -en ";5;045m▄\e[0m\e[0m\e[48;5;232m\e[38;5;033m▄\e[0m\e[0m\e"
    echo -en "[38;5;232m▄\e[0m                            \e[7m\e[38;"
    echo -en "5;033m▄\e[0m\e[0m\e[48;5;045m\e[38;5;045m▄\e[0m\e[0m\e["
    echo -en "48;5;045m\e[38;5;045m▄\e[0m\e[0m\e[48;5;045m\e[38;5;045"
    echo -en "m▄\e[0m\e[0m\e[48;5;033m\e[38;5;045m▄\e[0m\e[0m\e[48;5;"
    echo -en "045m\e[38;5;045m▄\e[0m\e[0m\e[48;5;045m\e[38;5;045m▄\e["
    echo -en "0m\e[0m\e[48;5;045m\e[38;5;045m▄\e[0m\e[0m\e[48;5;033m"
    echo -en "\e[38;5;045m▄\e[0m\e[0m\e[38;5;033m▄\e[0m"
    echo
    echo -en "                    \e[48;5;232m\e[38;5;232m▄\e[0m\e[0m"
    echo -en "\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;"
    echo -en "033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48"
    echo -en ";5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄"
    echo -en "\e[0m\e[0m\e[48;5;033m\e[38;5;232m▄\e[0m\e[0m\e[48;5;03"
    echo -en "3m\e[38;5;232m▄\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m"
    echo -en "\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;045m\e["
    echo -en "38;5;045m▄\e[0m\e[0m\e[48;5;045m\e[38;5;045m▄\e[0m\e[0m"
    echo -en "\e[48;5;045m\e[38;5;045m▄\e[0m\e[0m\e[48;5;033m\e[38;5;"
    echo -en "033m▄\e[0m\e[0m\e[48;5;232m\e[38;5;232m▄\e[0m\e[0m     "
    echo -en "                \e[7m\e[38;5;033m▄\e[0m\e[0m\e[7m\e[38;"
    echo -en "5;033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e["
    echo -en "48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;033"
    echo -en "m▄\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;"
    echo -en "033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄\e["
    echo -en "0m\e[0m\e[48;5;045m\e[38;5;045m▄\e[0m\e[0m\e[48;5;045m"
    echo -en "\e[38;5;045m▄\e[0m\e[0m\e[48;5;255m\e[38;5;045m▄\e[0m\e"
    echo -en "[0m\e[48;5;045m\e[38;5;255m▄\e[0m\e[0m\e[48;5;045m\e[38"
    echo -en ";5;255m▄\e[0m\e[0m\e[48;5;045m\e[38;5;045m▄\e[0m\e[0m\e"
    echo -en "[48;5;045m\e[38;5;045m▄\e[0m\e[0m\e[48;5;033m\e[38;5;04"
    echo -en "5m▄\e[0m\e[0m\e[48;5;045m\e[38;5;033m▄\e[0m\e[0m\e[48;5"
    echo -en ";033m\e[38;5;045m▄\e[0m\e[0m\e[38;5;033m▄\e[0m"
    echo
    echo -en "                   \e[48;5;232m\e[38;5;232m▄\e[0m\e[0m"
    echo -en "\e[48;5;045m\e[38;5;045m▄\e[0m\e[0m\e[48;5;045m\e[38;5;"
    echo -en "196m▄\e[0m\e[0m\e[48;5;045m\e[38;5;045m▄\e[0m\e[0m\e[48"
    echo -en ";5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;232m▄"
    echo -en "\e[0m\e[0m\e[48;5;232m\e[38;5;223m▄\e[0m\e[0m\e[48;5;22"
    echo -en "3m\e[38;5;255m▄\e[0m\e[0m\e[48;5;255m\e[38;5;255m▄\e[0m"
    echo -en "\e[0m\e[48;5;232m\e[38;5;232m▄\e[0m\e[0m\e[48;5;033m\e["
    echo -en "38;5;232m▄\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m"
    echo -en "\e[48;5;033m\e[38;5;232m▄\e[0m\e[0m\e[48;5;232m\e[38;5;"
    echo -en "255m▄\e[0m\e[0m\e[48;5;232m\e[38;5;232m▄\e[0m\e[0m\e[7m"
    echo -en "\e[38;5;232m▄\e[0m\e[0m                      \e[38;5;03"
    echo -en "3m▄\e[0m\e[38;5;033m▄\e[0m\e[38;5;033m▄\e[0m\e[48;5;033"
    echo -en "m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;045m▄\e[0m"
    echo -en "\e[0m\e[48;5;033m\e[38;5;045m▄\e[0m\e[0m\e[48;5;045m\e["
    echo -en "38;5;045m▄\e[0m\e[0m\e[48;5;045m\e[38;5;045m▄\e[0m\e[0m"
    echo -en "\e[48;5;045m\e[38;5;255m▄\e[0m\e[0m\e[48;5;045m\e[38;5;"
    echo -en "255m▄\e[0m\e[0m\e[48;5;255m\e[38;5;255m▄\e[0m\e[0m\e[48"
    echo -en ";5;255m\e[38;5;255m▄\e[0m\e[0m\e[48;5;255m\e[38;5;255m▄"
    echo -en "\e[0m\e[0m\e[48;5;045m\e[38;5;255m▄\e[0m\e[0m\e[48;5;04"
    echo -en "5m\e[38;5;045m▄\e[0m\e[0m\e[48;5;045m\e[38;5;045m▄\e[0m"
    echo -en "\e[0m\e[48;5;033m\e[38;5;045m▄\e[0m\e[0m\e[7m\e[38;5;04"
    echo -en "5m▄\e[0m\e[0m"
    echo
    echo -en "                  \e[38;5;232m▄\e[0m\e[48;5;232m\e[38;5"
    echo -en ";232m▄\e[0m\e[0m\e[48;5;045m\e[38;5;045m▄\e[0m\e[0m\e[4"
    echo -en "8;5;196m\e[38;5;196m▄\e[0m\e[0m\e[48;5;045m\e[38;5;045m"
    echo -en "▄\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;2"
    echo -en "32m\e[38;5;232m▄\e[0m\e[0m\e[48;5;223m\e[38;5;223m▄\e[0"
    echo -en "m\e[0m\e[48;5;255m\e[38;5;255m▄\e[0m\e[0m\e[48;5;255m\e"
    echo -en "[38;5;255m▄\e[0m\e[0m\e[48;5;232m\e[38;5;232m▄\e[0m\e[0"
    echo -en "m\e[48;5;255m\e[38;5;255m▄\e[0m\e[0m\e[48;5;232m\e[38;5"
    echo -en ";223m▄\e[0m\e[0m\e[48;5;232m\e[38;5;232m▄\e[0m\e[0m\e[4"
    echo -en "8;5;255m\e[38;5;255m▄\e[0m\e[0m\e[48;5;232m\e[38;5;232m"
    echo -en "▄\e[0m\e[0m                \e[38;5;033m▄\e[0m\e[38;5;03"
    echo -en "3m▄\e[0m\e[38;5;033m▄\e[0m\e[38;5;033m▄\e[0m\e[38;5;033"
    echo -en "m▄\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m"
    echo -en "\e[38;5;033m▄\e[0m\e[0m\e[48;5;045m\e[38;5;033m▄\e[0m\e"
    echo -en "[0m\e[48;5;045m\e[38;5;033m▄\e[0m\e[0m\e[48;5;045m\e[38"
    echo -en ";5;033m▄\e[0m\e[0m\e[48;5;045m\e[38;5;045m▄\e[0m\e[0m\e"
    echo -en "[48;5;045m\e[38;5;045m▄\e[0m\e[0m\e[48;5;045m\e[38;5;25"
    echo -en "5m▄\e[0m\e[0m\e[48;5;255m\e[38;5;255m▄\e[0m\e[0m\e[48;5"
    echo -en ";255m\e[38;5;255m▄\e[0m\e[0m\e[48;5;255m\e[38;5;255m▄\e"
    echo -en "[0m\e[0m\e[48;5;255m\e[38;5;255m▄\e[0m\e[0m\e[48;5;255m"
    echo -en "\e[38;5;045m▄\e[0m\e[0m\e[48;5;045m\e[38;5;045m▄\e[0m\e"
    echo -en "[0m\e[48;5;045m\e[38;5;045m▄\e[0m\e[0m\e[48;5;045m\e[38"
    echo -en ";5;045m▄\e[0m\e[0m\e[48;5;045m\e[38;5;033m▄\e[0m\e[0m\e"
    echo -en "[48;5;045m\e[38;5;033m▄\e[0m\e[0m\e[48;5;045m\e[38;5;03"
    echo -en "3m▄\e[0m\e[0m\e[48;5;033m\e[38;5;045m▄\e[0m\e[0m\e[38;5"
    echo -en ";033m▄\e[0m\e[38;5;033m▄\e[0m\e[48;5;033m\e[38;5;033m▄"
    echo -en "\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;03"
    echo -en "3m\e[38;5;033m▄\e[0m\e[0m\e[38;5;033m▄\e[0m"
    echo
    echo -en "               \e[38;5;232m▄\e[0m\e[48;5;232m\e[38;5;04"
    echo -en "5m▄\e[0m\e[0m\e[48;5;232m\e[38;5;045m▄\e[0m\e[0m\e[48;5"
    echo -en ";045m\e[38;5;045m▄\e[0m\e[0m\e[48;5;045m\e[38;5;045m▄\e"
    echo -en "[0m\e[0m\e[48;5;232m\e[38;5;045m▄\e[0m\e[0m\e[48;5;045m"
    echo -en "\e[38;5;232m▄\e[0m\e[0m\e[48;5;045m\e[38;5;232m▄\e[0m\e"
    echo -en "[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;232m\e[38"
    echo -en ";5;232m▄\e[0m\e[0m\e[48;5;223m\e[38;5;223m▄\e[0m\e[0m\e"
    echo -en "[48;5;223m\e[38;5;223m▄\e[0m\e[0m\e[48;5;255m\e[38;5;23"
    echo -en "2m▄\e[0m\e[0m\e[48;5;255m\e[38;5;232m▄\e[0m\e[0m\e[48;5"
    echo -en ";255m\e[38;5;223m▄\e[0m\e[0m\e[48;5;223m\e[38;5;223m▄\e"
    echo -en "[0m\e[0m\e[48;5;223m\e[38;5;223m▄\e[0m\e[0m\e[48;5;223m"
    echo -en "\e[38;5;223m▄\e[0m\e[0m\e[48;5;232m\e[38;5;232m▄\e[0m\e"
    echo -en "[0m \e[38;5;232m▄\e[0m\e[48;5;232m\e[38;5;033m▄\e[0m\e["
    echo -en "0m\e[48;5;232m\e[38;5;033m▄\e[0m\e[0m\e[48;5;232m\e[38;"
    echo -en "5;033m▄\e[0m\e[0m\e[48;5;232m\e[38;5;033m▄\e[0m\e[0m\e["
    echo -en "48;5;232m\e[38;5;033m▄\e[0m\e[0m\e[48;5;232m\e[38;5;033"
    echo -en "m▄\e[0m\e[0m\e[48;5;232m\e[38;5;232m▄\e[0m\e[0m\e[38;5;"
    echo -en "232m▄\e[0m        \e[7m\e[38;5;033m▄\e[0m\e[0m\e[7m\e[3"
    echo -en "8;5;033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m"
    echo -en "\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;"
    echo -en "033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48"
    echo -en ";5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;045m▄"
    echo -en "\e[0m\e[0m\e[48;5;033m\e[38;5;045m▄\e[0m\e[0m\e[48;5;04"
    echo -en "5m\e[38;5;255m▄\e[0m\e[0m\e[48;5;045m\e[38;5;255m▄\e[0m"
    echo -en "\e[0m\e[48;5;045m\e[38;5;255m▄\e[0m\e[0m\e[48;5;255m\e["
    echo -en "38;5;231m▄\e[0m\e[0m\e[48;5;255m\e[38;5;231m▄\e[0m\e[0m"
    echo -en "\e[48;5;045m\e[38;5;255m▄\e[0m\e[0m\e[48;5;045m\e[38;5;"
    echo -en "255m▄\e[0m\e[0m\e[48;5;045m\e[38;5;045m▄\e[0m\e[0m\e[48"
    echo -en ";5;045m\e[38;5;045m▄\e[0m\e[0m\e[38;5;045m▄\e[0m\e[38;5"
    echo -en ";045m▄\e[0m \e[38;5;033m▄\e[0m\e[38;5;033m▄\e[0m\e[38;5"
    echo -en ";033m▄\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;0"
    echo -en "33m\e[38;5;033m▄\e[0m\e[0m\e[48;5;045m\e[38;5;045m▄\e[0"
    echo -en "m\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e"
    echo -en "[38;5;033m▄\e[0m\e[0m"
    echo
    echo -en "             \e[38;5;232m▄\e[0m\e[48;5;232m\e[38;5;033m"
    echo -en "▄\e[0m\e[0m\e[48;5;232m\e[38;5;033m▄\e[0m\e[0m\e[48;5;2"
    echo -en "32m\e[38;5;033m▄\e[0m\e[0m\e[48;5;232m\e[38;5;033m▄\e[0"
    echo -en "m\e[0m\e[48;5;045m\e[38;5;232m▄\e[0m\e[0m\e[48;5;045m\e"
    echo -en "[38;5;045m▄\e[0m\e[0m\e[48;5;045m\e[38;5;045m▄\e[0m\e[0"
    echo -en "m\e[48;5;045m\e[38;5;045m▄\e[0m\e[0m\e[48;5;232m\e[38;5"
    echo -en ";033m▄\e[0m\e[0m\e[48;5;232m\e[38;5;232m▄\e[0m\e[0m\e[4"
    echo -en "8;5;033m\e[38;5;232m▄\e[0m\e[0m\e[48;5;232m\e[38;5;033m"
    echo -en "▄\e[0m\e[0m\e[48;5;223m\e[38;5;232m▄\e[0m\e[0m\e[48;5;2"
    echo -en "23m\e[38;5;223m▄\e[0m\e[0m\e[48;5;223m\e[38;5;223m▄\e[0"
    echo -en "m\e[0m\e[48;5;232m\e[38;5;223m▄\e[0m\e[0m\e[48;5;223m\e"
    echo -en "[38;5;223m▄\e[0m\e[0m\e[48;5;223m\e[38;5;223m▄\e[0m\e[0"
    echo -en "m\e[48;5;223m\e[38;5;232m▄\e[0m\e[0m\e[48;5;232m\e[38;5"
    echo -en ";045m▄\e[0m\e[0m\e[48;5;232m\e[38;5;232m▄\e[0m\e[0m\e[4"
    echo -en "8;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;033m"
    echo -en "▄\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;0"
    echo -en "33m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄\e[0"
    echo -en "m\e[0m\e[48;5;033m\e[38;5;232m▄\e[0m\e[0m\e[48;5;232m\e"
    echo -en "[38;5;045m▄\e[0m\e[0m\e[48;5;045m\e[38;5;196m▄\e[0m\e[0"
    echo -en "m\e[48;5;045m\e[38;5;232m▄\e[0m\e[0m\e[48;5;232m\e[38;5"
    echo -en ";045m▄\e[0m\e[0m\e[38;5;232m▄\e[0m     \e[38;5;033m▄\e["
    echo -en "0m\e[38;5;033m▄\e[0m\e[38;5;045m▄\e[0m\e[38;5;045m▄\e[0"
    echo -en "m\e[48;5;033m\e[38;5;045m▄\e[0m\e[0m\e[48;5;033m\e[38;5"
    echo -en ";255m▄\e[0m\e[0m\e[48;5;045m\e[38;5;255m▄\e[0m\e[0m\e[4"
    echo -en "8;5;045m\e[38;5;255m▄\e[0m\e[0m\e[48;5;045m\e[38;5;255m"
    echo -en "▄\e[0m\e[0m\e[48;5;255m\e[38;5;231m▄\e[0m\e[0m\e[48;5;2"
    echo -en "55m\e[38;5;231m▄\e[0m\e[0m\e[48;5;231m\e[38;5;231m▄\e[0"
    echo -en "m\e[0m\e[48;5;231m\e[38;5;231m▄\e[0m\e[0m\e[48;5;231m\e"
    echo -en "[38;5;231m▄\e[0m\e[0m\e[48;5;231m\e[38;5;231m▄\e[0m\e[0"
    echo -en "m\e[48;5;231m\e[38;5;231m▄\e[0m\e[0m\e[48;5;231m\e[38;5"
    echo -en ";255m▄\e[0m\e[0m\e[48;5;231m\e[38;5;255m▄\e[0m\e[0m\e[4"
    echo -en "8;5;231m\e[38;5;045m▄\e[0m\e[0m\e[48;5;255m\e[38;5;045m"
    echo -en "▄\e[0m\e[0m\e[7m\e[38;5;255m▄\e[0m\e[0m\e[48;5;045m\e[3"
    echo -en "8;5;033m▄\e[0m\e[0m\e[48;5;045m\e[38;5;045m▄\e[0m\e[0m"
    echo -en "\e[48;5;045m\e[38;5;045m▄\e[0m\e[0m\e[48;5;045m\e[38;5;"
    echo -en "255m▄\e[0m\e[0m\e[48;5;045m\e[38;5;255m▄\e[0m\e[0m\e[48"
    echo -en ";5;045m\e[38;5;045m▄\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄"
    echo -en "\e[0m\e[0m\e[48;5;045m\e[38;5;045m▄\e[0m\e[0m\e[48;5;03"
    echo -en "3m\e[38;5;033m▄\e[0m\e[0m"
    echo
    echo -en "             \e[48;5;232m\e[38;5;232m▄\e[0m\e[0m\e[48;5"
    echo -en ";033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄\e"
    echo -en "[0m\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m"
    echo -en "\e[38;5;232m▄\e[0m\e[0m\e[48;5;232m\e[38;5;033m▄\e[0m\e"
    echo -en "[0m\e[48;5;232m\e[38;5;033m▄\e[0m\e[0m\e[48;5;232m\e[38"
    echo -en ";5;033m▄\e[0m\e[0m\e[48;5;045m\e[38;5;232m▄\e[0m\e[0m\e"
    echo -en "[48;5;045m\e[38;5;045m▄\e[0m\e[0m\e[48;5;033m\e[38;5;04"
    echo -en "5m▄\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5"
    echo -en ";232m\e[38;5;033m▄\e[0m\e[0m\e[48;5;232m\e[38;5;033m▄\e"
    echo -en "[0m\e[0m\e[48;5;232m\e[38;5;033m▄\e[0m\e[0m\e[48;5;232m"
    echo -en "\e[38;5;045m▄\e[0m\e[0m\e[48;5;232m\e[38;5;045m▄\e[0m\e"
    echo -en "[0m\e[48;5;232m\e[38;5;045m▄\e[0m\e[0m\e[48;5;232m\e[38"
    echo -en ";5;045m▄\e[0m\e[0m\e[48;5;045m\e[38;5;045m▄\e[0m\e[0m\e"
    echo -en "[48;5;045m\e[38;5;045m▄\e[0m\e[0m\e[48;5;232m\e[38;5;23"
    echo -en "2m▄\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5"
    echo -en ";033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄\e"
    echo -en "[0m\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m"
    echo -en "\e[38;5;033m▄\e[0m\e[0m\e[48;5;232m\e[38;5;232m▄\e[0m\e"
    echo -en "[0m\e[48;5;045m\e[38;5;045m▄\e[0m\e[0m\e[48;5;196m\e[38"
    echo -en ";5;196m▄\e[0m\e[0m\e[48;5;232m\e[38;5;232m▄\e[0m\e[0m\e"
    echo -en "[48;5;045m\e[38;5;045m▄\e[0m\e[0m\e[48;5;232m\e[38;5;23"
    echo -en "2m▄\e[0m\e[0m \e[7m\e[38;5;033m▄\e[0m\e[0m\e[7m\e[38;5;"
    echo -en "033m▄\e[0m\e[0m\e[7m\e[38;5;033m▄\e[0m\e[0m\e[7m\e[38;5"
    echo -en ";045m▄\e[0m\e[0m\e[48;5;045m\e[38;5;033m▄\e[0m\e[0m\e[4"
    echo -en "8;5;255m\e[38;5;033m▄\e[0m\e[0m\e[48;5;255m\e[38;5;045m"
    echo -en "▄\e[0m\e[0m\e[48;5;231m\e[38;5;045m▄\e[0m\e[0m\e[48;5;2"
    echo -en "31m\e[38;5;045m▄\e[0m\e[0m\e[48;5;231m\e[38;5;255m▄\e[0"
    echo -en "m\e[0m\e[48;5;231m\e[38;5;255m▄\e[0m\e[0m\e[48;5;231m\e"
    echo -en "[38;5;255m▄\e[0m\e[0m\e[48;5;231m\e[38;5;255m▄\e[0m\e[0"
    echo -en "m\e[48;5;231m\e[38;5;231m▄\e[0m\e[0m\e[48;5;231m\e[38;5"
    echo -en ";231m▄\e[0m\e[0m\e[48;5;231m\e[38;5;231m▄\e[0m\e[0m\e[4"
    echo -en "8;5;231m\e[38;5;231m▄\e[0m\e[0m\e[48;5;231m\e[38;5;231m"
    echo -en "▄\e[0m\e[0m\e[48;5;255m\e[38;5;231m▄\e[0m\e[0m\e[48;5;0"
    echo -en "45m\e[38;5;231m▄\e[0m\e[0m\e[48;5;045m\e[38;5;255m▄\e[0"
    echo -en "m\e[0m\e[48;5;045m\e[38;5;255m▄\e[0m\e[0m\e[38;5;045m▄"
    echo -en "\e[0m\e[38;5;045m▄\e[0m \e[48;5;033m\e[38;5;033m▄\e[0m"
    echo -en "\e[0m\e[48;5;045m\e[38;5;045m▄\e[0m\e[0m\e[48;5;255m\e["
    echo -en "38;5;045m▄\e[0m\e[0m\e[48;5;255m\e[38;5;255m▄\e[0m\e[0m"
    echo -en "\e[48;5;255m\e[38;5;255m▄\e[0m\e[0m\e[48;5;255m\e[38;5;"
    echo -en "045m▄\e[0m\e[0m\e[48;5;045m\e[38;5;033m▄\e[0m\e[0m\e[48"
    echo -en ";5;045m\e[38;5;045m▄\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄"
    echo -en "\e[0m\e[0m"
    echo
    echo -en "             \e[48;5;232m\e[38;5;232m▄\e[0m\e[0m\e[48;5"
    echo -en ";033m\e[38;5;232m▄\e[0m\e[0m\e[48;5;033m\e[38;5;232m▄\e"
    echo -en "[0m\e[0m\e[48;5;232m\e[38;5;033m▄\e[0m\e[0m\e[48;5;232m"
    echo -en "\e[38;5;232m▄\e[0m\e[0m\e[48;5;033m\e[38;5;232m▄\e[0m\e"
    echo -en "[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e[38"
    echo -en ";5;033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e"
    echo -en "[48;5;232m\e[38;5;232m▄\e[0m\e[0m\e[48;5;045m\e[38;5;04"
    echo -en "5m▄\e[0m\e[0m\e[48;5;045m\e[38;5;045m▄\e[0m\e[0m\e[48;5"
    echo -en ";045m\e[38;5;045m▄\e[0m\e[0m\e[48;5;045m\e[38;5;045m▄\e"
    echo -en "[0m\e[0m\e[48;5;045m\e[38;5;045m▄\e[0m\e[0m\e[48;5;045m"
    echo -en "\e[38;5;232m▄\e[0m\e[0m\e[7m\e[38;5;232m▄\e[0m\e[0m\e[7"
    echo -en "m\e[38;5;232m▄\e[0m\e[0m\e[7m\e[38;5;232m▄\e[0m\e[0m\e["
    echo -en "7m\e[38;5;232m▄\e[0m\e[0m\e[7m\e[38;5;232m▄\e[0m\e[0m\e"
    echo -en "[7m\e[38;5;232m▄\e[0m\e[0m\e[48;5;033m\e[38;5;232m▄\e[0"
    echo -en "m\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e"
    echo -en "[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0"
    echo -en "m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e[38;5"
    echo -en ";033m▄\e[0m\e[0m\e[48;5;232m\e[38;5;033m▄\e[0m\e[0m\e[4"
    echo -en "8;5;045m\e[38;5;232m▄\e[0m\e[0m\e[48;5;045m\e[38;5;232m"
    echo -en "▄\e[0m\e[0m\e[7m\e[38;5;232m▄\e[0m\e[0m         \e[38;5"
    echo -en ";033m▄\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;0"
    echo -en "33m\e[38;5;033m▄\e[0m\e[0m\e[48;5;045m\e[38;5;033m▄\e[0"
    echo -en "m\e[0m\e[48;5;045m\e[38;5;033m▄\e[0m\e[0m\e[48;5;045m\e"
    echo -en "[38;5;045m▄\e[0m\e[0m\e[48;5;255m\e[38;5;045m▄\e[0m\e[0"
    echo -en "m\e[48;5;255m\e[38;5;255m▄\e[0m\e[0m\e[48;5;231m\e[38;5"
    echo -en ";255m▄\e[0m\e[0m\e[48;5;231m\e[38;5;255m▄\e[0m\e[0m\e[4"
    echo -en "8;5;231m\e[38;5;231m▄\e[0m\e[0m\e[48;5;231m\e[38;5;231m"
    echo -en "▄\e[0m\e[0m\e[48;5;231m\e[38;5;255m▄\e[0m\e[0m\e[48;5;2"
    echo -en "31m\e[38;5;255m▄\e[0m\e[0m\e[48;5;231m\e[38;5;045m▄\e[0"
    echo -en "m\e[0m\e[48;5;231m\e[38;5;045m▄\e[0m\e[0m\e[48;5;255m\e"
    echo -en "[38;5;045m▄\e[0m\e[0m\e[48;5;255m\e[38;5;045m▄\e[0m\e[0"
    echo -en "m\e[7m\e[38;5;045m▄\e[0m\e[0m\e[48;5;045m\e[38;5;033m▄"
    echo -en "\e[0m\e[0m\e[48;5;045m\e[38;5;033m▄\e[0m\e[0m\e[48;5;04"
    echo -en "5m\e[38;5;033m▄\e[0m\e[0m\e[48;5;045m\e[38;5;033m▄\e[0m"
    echo -en "\e[0m\e[48;5;045m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e["
    echo -en "38;5;045m▄\e[0m\e[0m\e[48;5;045m\e[38;5;033m▄\e[0m\e[0m"
    echo -en "\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m"
    echo
    echo -en "              \e[48;5;232m\e[38;5;232m▄\e[0m\e[0m\e[48;"
    echo -en "5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄"
    echo -en "\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;03"
    echo -en "3m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m"
    echo -en "\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e["
    echo -en "38;5;232m▄\e[0m\e[0m\e[48;5;232m\e[38;5;232m▄\e[0m\e[0m"
    echo -en "\e[48;5;045m\e[38;5;232m▄\e[0m\e[0m\e[48;5;045m\e[38;5;"
    echo -en "232m▄\e[0m\e[0m\e[48;5;045m\e[38;5;232m▄\e[0m\e[0m\e[48"
    echo -en ";5;045m\e[38;5;232m▄\e[0m\e[0m\e[7m\e[38;5;232m▄\e[0m\e"
    echo -en "[0m        \e[7m\e[38;5;232m▄\e[0m\e[0m\e[7m\e[38;5;232"
    echo -en "m▄\e[0m\e[0m\e[7m\e[38;5;232m▄\e[0m\e[0m\e[7m\e[38;5;23"
    echo -en "2m▄\e[0m\e[0m\e[7m\e[38;5;232m▄\e[0m\e[0m\e[7m\e[38;5;2"
    echo -en "32m▄\e[0m\e[0m\e[7m\e[38;5;232m▄\e[0m\e[0m       \e[38;"
    echo -en "5;033m▄\e[0m\e[38;5;033m▄\e[0m\e[48;5;033m\e[38;5;033m▄"
    echo -en "\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;03"
    echo -en "3m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m"
    echo -en "\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e["
    echo -en "38;5;033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m"
    echo -en "\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;"
    echo -en "045m▄\e[0m\e[0m\e[48;5;045m\e[38;5;045m▄\e[0m\e[0m\e[48"
    echo -en ";5;045m\e[38;5;255m▄\e[0m\e[0m\e[48;5;045m\e[38;5;255m▄"
    echo -en "\e[0m\e[0m\e[48;5;255m\e[38;5;255m▄\e[0m\e[0m\e[48;5;25"
    echo -en "5m\e[38;5;255m▄\e[0m\e[0m\e[48;5;045m\e[38;5;255m▄\e[0m"
    echo -en "\e[0m\e[48;5;045m\e[38;5;045m▄\e[0m\e[0m\e[48;5;045m\e["
    echo -en "38;5;045m▄\e[0m\e[0m\e[48;5;045m\e[38;5;045m▄\e[0m\e[0m"
    echo -en "\e[38;5;045m▄\e[0m\e[38;5;033m▄\e[0m\e[38;5;033m▄\e[0m"
    echo -en "\e[38;5;033m▄\e[0m\e[38;5;045m▄\e[0m\e[38;5;033m▄\e[0m"
    echo -en "\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;"
    echo -en "033m▄\e[0m\e[0m\e[48;5;045m\e[38;5;033m▄\e[0m\e[0m\e[48"
    echo -en ";5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄"
    echo -en "\e[0m\e[0m"
    echo
    echo -en "               \e[7m\e[38;5;232m▄\e[0m\e[0m\e[7m\e[38;5"
    echo -en ";232m▄\e[0m\e[0m\e[48;5;033m\e[38;5;232m▄\e[0m\e[0m\e[4"
    echo -en "8;5;033m\e[38;5;232m▄\e[0m\e[0m\e[48;5;033m\e[38;5;232m"
    echo -en "▄\e[0m\e[0m\e[48;5;232m\e[38;5;033m▄\e[0m\e[0m\e[48;5;2"
    echo -en "32m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄\e[0"
    echo -en "m\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e"
    echo -en "[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0"
    echo -en "m\e[48;5;232m\e[38;5;232m▄\e[0m\e[0m\e[38;5;232m▄\e[0m "
    echo -en "                          \e[7m\e[38;5;033m▄\e[0m\e[0m"
    echo -en "\e[7m\e[38;5;033m▄\e[0m\e[0m\e[48;5;045m\e[38;5;033m▄\e"
    echo -en "[0m\e[0m\e[48;5;045m\e[38;5;033m▄\e[0m\e[0m\e[48;5;045m"
    echo -en "\e[38;5;033m▄\e[0m\e[0m\e[48;5;045m\e[38;5;033m▄\e[0m\e"
    echo -en "[0m\e[48;5;045m\e[38;5;045m▄\e[0m\e[0m\e[48;5;045m\e[38"
    echo -en ";5;045m▄\e[0m\e[0m\e[48;5;255m\e[38;5;045m▄\e[0m\e[0m\e"
    echo -en "[48;5;255m\e[38;5;045m▄\e[0m\e[0m\e[48;5;255m\e[38;5;25"
    echo -en "5m▄\e[0m\e[0m\e[48;5;255m\e[38;5;255m▄\e[0m\e[0m\e[48;5"
    echo -en ";255m\e[38;5;255m▄\e[0m\e[0m\e[48;5;045m\e[38;5;255m▄\e"
    echo -en "[0m\e[0m\e[48;5;045m\e[38;5;255m▄\e[0m\e[0m\e[48;5;045m"
    echo -en "\e[38;5;255m▄\e[0m\e[0m\e[48;5;045m\e[38;5;045m▄\e[0m\e"
    echo -en "[0m\e[48;5;045m\e[38;5;045m▄\e[0m\e[0m\e[48;5;045m\e[38"
    echo -en ";5;045m▄\e[0m\e[0m\e[7m\e[38;5;033m▄\e[0m\e[0m  \e[7m\e"
    echo -en "[38;5;033m▄\e[0m\e[0m\e[7m\e[38;5;033m▄\e[0m\e[0m\e[7m"
    echo -en "\e[38;5;033m▄\e[0m\e[0m"
    echo
    echo -en "               \e[38;5;232m▄\e[0m\e[48;5;232m\e[38;5;04"
    echo -en "5m▄\e[0m\e[0m\e[48;5;045m\e[38;5;045m▄\e[0m\e[0m\e[48;5"
    echo -en ";045m\e[38;5;045m▄\e[0m\e[0m\e[48;5;232m\e[38;5;045m▄\e"
    echo -en "[0m\e[0m\e[48;5;033m\e[38;5;232m▄\e[0m\e[0m\e[48;5;033m"
    echo -en "\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e"
    echo -en "[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e[38"
    echo -en ";5;232m▄\e[0m\e[0m\e[48;5;232m\e[38;5;045m▄\e[0m\e[0m\e"
    echo -en "[48;5;045m\e[38;5;045m▄\e[0m\e[0m\e[48;5;045m\e[38;5;04"
    echo -en "5m▄\e[0m\e[0m\e[48;5;232m\e[38;5;045m▄\e[0m\e[0m\e[38;5"
    echo -en ";232m▄\e[0m\e[38;5;232m▄\e[0m                          "
    echo -en " \e[38;5;033m▄\e[0m\e[38;5;033m▄\e[0m\e[48;5;033m\e[38;"
    echo -en "5;033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e["
    echo -en "48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;045m\e[38;5;033"
    echo -en "m▄\e[0m\e[0m\e[48;5;045m\e[38;5;045m▄\e[0m\e[0m\e[48;5;"
    echo -en "045m\e[38;5;045m▄\e[0m\e[0m\e[48;5;045m\e[38;5;045m▄\e["
    echo -en "0m\e[0m\e[48;5;255m\e[38;5;255m▄\e[0m\e[0m\e[48;5;255m"
    echo -en "\e[38;5;255m▄\e[0m\e[0m\e[48;5;255m\e[38;5;045m▄\e[0m\e"
    echo -en "[0m\e[48;5;045m\e[38;5;045m▄\e[0m\e[0m\e[48;5;045m\e[38"
    echo -en ";5;045m▄\e[0m\e[0m\e[48;5;045m\e[38;5;033m▄\e[0m\e[0m\e"
    echo -en "[48;5;033m\e[38;5;045m▄\e[0m\e[0m\e[48;5;045m\e[38;5;03"
    echo -en "3m▄\e[0m\e[0m"
    echo
    echo -en "            \e[38;5;232m▄\e[0m\e[48;5;232m\e[38;5;033m▄"
    echo -en "\e[0m\e[0m\e[48;5;232m\e[38;5;033m▄\e[0m\e[0m\e[48;5;04"
    echo -en "5m\e[38;5;232m▄\e[0m\e[0m\e[48;5;045m\e[38;5;045m▄\e[0m"
    echo -en "\e[0m\e[48;5;045m\e[38;5;045m▄\e[0m\e[0m\e[48;5;045m\e["
    echo -en "38;5;045m▄\e[0m\e[0m\e[48;5;045m\e[38;5;232m▄\e[0m\e[0m"
    echo -en "\e[7m\e[38;5;232m▄\e[0m\e[0m\e[7m\e[38;5;232m▄\e[0m\e[0"
    echo -en "m\e[7m\e[38;5;232m▄\e[0m\e[0m\e[7m\e[38;5;232m▄\e[0m\e["
    echo -en "0m\e[7m\e[38;5;232m▄\e[0m\e[0m\e[48;5;045m\e[38;5;232m▄"
    echo -en "\e[0m\e[0m\e[48;5;045m\e[38;5;045m▄\e[0m\e[0m\e[48;5;04"
    echo -en "5m\e[38;5;232m▄\e[0m\e[0m\e[48;5;232m\e[38;5;033m▄\e[0m"
    echo -en "\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e["
    echo -en "38;5;033m▄\e[0m\e[0m\e[48;5;232m\e[38;5;033m▄\e[0m\e[0m"
    echo -en "\e[38;5;232m▄\e[0m                       \e[7m\e[38;5;0"
    echo -en "33m▄\e[0m\e[0m\e[7m\e[38;5;033m▄\e[0m\e[0m\e[7m\e[38;5;"
    echo -en "033m▄\e[0m\e[0m\e[7m\e[38;5;033m▄\e[0m\e[0m\e[7m\e[38;5"
    echo -en ";033m▄\e[0m\e[0m\e[7m\e[38;5;033m▄\e[0m\e[0m\e[7m\e[38;"
    echo -en "5;033m▄\e[0m\e[0m\e[7m\e[38;5;033m▄\e[0m\e[0m\e[48;5;04"
    echo -en "5m\e[38;5;045m▄\e[0m\e[0m\e[48;5;045m\e[38;5;045m▄\e[0m"
    echo -en "\e[0m\e[48;5;255m\e[38;5;045m▄\e[0m\e[0m\e[48;5;045m\e["
    echo -en "38;5;045m▄\e[0m\e[0m\e[48;5;045m\e[38;5;045m▄\e[0m\e[0m"
    echo -en "\e[48;5;045m\e[38;5;045m▄\e[0m\e[0m\e[48;5;045m\e[38;5;"
    echo -en "045m▄\e[0m\e[0m\e[48;5;033m\e[38;5;045m▄\e[0m\e[0m\e[48"
    echo -en ";5;045m\e[38;5;033m▄\e[0m\e[0m\e[7m\e[38;5;033m▄\e[0m\e"
    echo -en "[0m"
    echo
    echo -en "          \e[38;5;232m▄\e[0m\e[48;5;232m\e[38;5;033m▄\e"
    echo -en "[0m\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m"
    echo -en "\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e"
    echo -en "[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;232m\e[38"
    echo -en ";5;033m▄\e[0m\e[0m\e[48;5;045m\e[38;5;232m▄\e[0m\e[0m\e"
    echo -en "[7m\e[38;5;232m▄\e[0m\e[0m     \e[38;5;232m▄\e[0m\e[48;"
    echo -en "5;232m\e[38;5;232m▄\e[0m\e[0m\e[48;5;232m\e[38;5;033m▄"
    echo -en "\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;03"
    echo -en "3m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m"
    echo -en "\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e["
    echo -en "38;5;033m▄\e[0m\e[0m\e[48;5;232m\e[38;5;232m▄\e[0m\e[0m"
    echo -en "                              \e[48;5;033m\e[38;5;045m▄"
    echo -en "\e[0m\e[0m\e[48;5;045m\e[38;5;045m▄\e[0m\e[0m\e[48;5;04"
    echo -en "5m\e[38;5;045m▄\e[0m\e[0m\e[7m\e[38;5;045m▄\e[0m\e[0m\e"
    echo -en "[7m\e[38;5;033m▄\e[0m\e[0m\e[48;5;045m\e[38;5;045m▄\e[0"
    echo -en "m\e[0m\e[48;5;045m\e[38;5;045m▄\e[0m\e[0m\e[48;5;045m\e"
    echo -en "[38;5;033m▄\e[0m\e[0m\e[7m\e[38;5;033m▄\e[0m\e[0m"
    echo
    echo -en "       \e[38;5;232m▄\e[0m\e[38;5;232m▄\e[0m\e[48;5;232m"
    echo -en "\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e"
    echo -en "[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e[38"
    echo -en ";5;033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e"
    echo -en "[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;03"
    echo -en "3m▄\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5"
    echo -en ";232m\e[38;5;232m▄\e[0m\e[0m     \e[38;5;232m▄\e[0m\e[4"
    echo -en "8;5;232m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;033m"
    echo -en "▄\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;0"
    echo -en "33m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄\e[0"
    echo -en "m\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e"
    echo -en "[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;232m▄\e[0m\e[0"
    echo -en "m\e[48;5;232m\e[38;5;232m▄\e[0m\e[0m                   "
    echo -en "          \e[48;5;033m\e[38;5;045m▄\e[0m\e[0m\e[7m\e[38"
    echo -en ";5;045m▄\e[0m\e[0m\e[7m\e[38;5;033m▄\e[0m\e[0m  \e[48;5"
    echo -en ";033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;045m\e[38;5;033m▄\e"
    echo -en "[0m\e[0m\e[7m\e[38;5;033m▄\e[0m\e[0m"
    echo
    echo -en "    \e[38;5;232m▄\e[0m\e[38;5;232m▄\e[0m\e[48;5;232m\e["
    echo -en "38;5;033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m"
    echo -en "\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;232m\e[38;5;"
    echo -en "033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;232m▄\e[0m\e[0m\e[48"
    echo -en ";5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄"
    echo -en "\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;03"
    echo -en "3m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m"
    echo -en "\e[0m\e[48;5;033m\e[38;5;232m▄\e[0m\e[0m\e[7m\e[38;5;23"
    echo -en "2m▄\e[0m\e[0m    \e[38;5;232m▄\e[0m\e[48;5;232m\e[38;5;"
    echo -en "033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48"
    echo -en ";5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄"
    echo -en "\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;03"
    echo -en "3m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;232m▄\e[0m"
    echo -en "\e[0m\e[48;5;232m\e[38;5;033m▄\e[0m\e[0m\e[48;5;232m\e["
    echo -en "38;5;033m▄\e[0m\e[0m\e[48;5;232m\e[38;5;033m▄\e[0m\e[0m"
    echo -en "\e[48;5;232m\e[38;5;033m▄\e[0m\e[0m\e[38;5;232m▄\e[0m  "
    echo -en "                        \e[7m\e[38;5;045m▄\e[0m\e[0m   "
    echo -en " \e[7m\e[38;5;033m▄\e[0m\e[0m"
    echo
    echo -en "  \e[38;5;232m▄\e[0m\e[48;5;232m\e[38;5;033m▄\e[0m\e[0m"
    echo -en "\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;"
    echo -en "033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48"
    echo -en ";5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄"
    echo -en "\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;03"
    echo -en "3m\e[38;5;033m▄\e[0m\e[0m\e[48;5;232m\e[38;5;033m▄\e[0m"
    echo -en "\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e["
    echo -en "38;5;033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m"
    echo -en "\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;232m\e[38;5;"
    echo -en "232m▄\e[0m\e[0m     \e[48;5;232m\e[38;5;232m▄\e[0m\e[0m"
    echo -en "\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;"
    echo -en "033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48"
    echo -en ";5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄"
    echo -en "\e[0m\e[0m\e[48;5;232m\e[38;5;033m▄\e[0m\e[0m\e[48;5;03"
    echo -en "3m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m"
    echo -en "\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;033m\e["
    echo -en "38;5;033m▄\e[0m\e[0m\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m"
    echo -en "\e[48;5;033m\e[38;5;033m▄\e[0m\e[0m\e[48;5;232m\e[38;5;"
    echo -en "033m▄\e[0m\e[0m\e[38;5;232m▄\e[0m"
    echo
    echo -en " \e[48;5;232m\e[38;5;232m▄\e[0m\e[0m\e[48;5;033m\e[38;5"
    echo -en ";232m▄\e[0m\e[0m\e[48;5;033m\e[38;5;232m▄\e[0m\e[0m\e[4"
    echo -en "8;5;033m\e[38;5;232m▄\e[0m\e[0m\e[48;5;033m\e[38;5;232m"
    echo -en "▄\e[0m\e[0m\e[48;5;033m\e[38;5;232m▄\e[0m\e[0m\e[48;5;0"
    echo -en "33m\e[38;5;232m▄\e[0m\e[0m\e[48;5;033m\e[38;5;232m▄\e[0"
    echo -en "m\e[0m\e[48;5;033m\e[38;5;232m▄\e[0m\e[0m\e[48;5;033m\e"
    echo -en "[38;5;232m▄\e[0m\e[0m\e[48;5;033m\e[38;5;232m▄\e[0m\e[0"
    echo -en "m\e[48;5;033m\e[38;5;232m▄\e[0m\e[0m\e[48;5;033m\e[38;5"
    echo -en ";232m▄\e[0m\e[0m\e[48;5;033m\e[38;5;232m▄\e[0m\e[0m\e[4"
    echo -en "8;5;232m\e[38;5;232m▄\e[0m\e[0m      \e[48;5;232m\e[38;"
    echo -en "5;232m▄\e[0m\e[0m\e[48;5;033m\e[38;5;232m▄\e[0m\e[0m\e["
    echo -en "48;5;033m\e[38;5;232m▄\e[0m\e[0m\e[48;5;033m\e[38;5;232"
    echo -en "m▄\e[0m\e[0m\e[48;5;033m\e[38;5;232m▄\e[0m\e[0m\e[48;5;"
    echo -en "033m\e[38;5;232m▄\e[0m\e[0m\e[48;5;033m\e[38;5;232m▄\e["
    echo -en "0m\e[0m\e[48;5;033m\e[38;5;232m▄\e[0m\e[0m\e[48;5;033m"
    echo -en "\e[38;5;232m▄\e[0m\e[0m\e[48;5;033m\e[38;5;232m▄\e[0m\e"
    echo -en "[0m\e[48;5;033m\e[38;5;232m▄\e[0m\e[0m\e[48;5;033m\e[38"
    echo -en ";5;232m▄\e[0m\e[0m\e[48;5;033m\e[38;5;232m▄\e[0m\e[0m\e"
    echo -en "[48;5;033m\e[38;5;232m▄\e[0m\e[0m\e[48;5;033m\e[38;5;23"
    echo -en "2m▄\e[0m\e[0m\e[48;5;232m\e[38;5;232m▄\e[0m\e[0m"
    echo
    echo
}

read_resume_file() {
    host="$(json_get "host")"
    local ignore
    while read -r ignore; do
        ignores+=("$ignore")
    done < <(json_get "ignores[]"); unset ignore
    simulate="$(json_get "simulate")"
    tls="$(json_get "tls")"
    local wordlist
    while read -r wordlist; do
        wordlists+=("$wordlist")
    done < <(json_get "wordlists[]"); unset wordlist
}

# summarize_results() {
#     [[ -n $summarize ]] || return
#     [[ -f "$results" ]] || return
#
#     info "Summarizing results"
#     while read -r result; do
#         good "${result:4}"
#     done < <(grep -oPs "\[\+\].+" $results | sort -u); unset result
# }

usage() {
    [[ $1 -ne 0 ]] || logo >&2
    cat <<EOF
Usage: ${0##*/} [OPTIONS] <host/ip>[:port][/path][?query]

Fuzz paths on a webserver. By default, MegaBuster will try to use the
directory-list-2.3-medium.txt list from DirBuster and the big.txt and
common.txt lists from dirb.

Options:
    -a, --apend          Append user specified lists to the default
    -c, --cache          Cache locations of defaults lists
    -h, --help           Display this help message
    -i, --ignore=CODE    Ignore specified return codes (can be used
                         more than once)
    -l, --list=LIST      Use the specified wordlist (can be used more
                         than once)
    --nocolor            Disable colorized output
    -p, --proxy=PROXY    Proxy traffic through PROXY
    -r, --resume         Resume from a previous run
    --simulate           Simulate output but do nothing
    -t, --threads=NUM    Use specied number of threads (default: 32)
    --timeout=SECS       Use specified curl timeout (default: none)
    --tls                Use TLS connection (https)
    -v, --verbose        Do not hide parallel errors

EOF
    exit "$1"
}

write_resume_file() {
    [[ -n $cache ]] || return
    [[ -n $json ]] || return
    rm -rf "$cache"
    mkdir -p "$cache"

    cat >"$json" <<EOF
{
  "host": "${host:-${simulate:+simulation}}",
  "ignores": [
$(
    for i in $(seq 1 ${#ignores[@]}); do
        echo "    \"${ignores[$i - 1]}\"${ignores[$i]:+,}"
    done; unset i
)
  ],
  "simulate": "$simulate",
  "tls": "$tls",
  "wordlists": [
$(
    for i in $(seq 1 ${#wordlists[@]}); do
        echo "    \"${wordlists[$i - 1]}\"${wordlists[$i]:+,}"
    done; unset i
)
  ]
}
EOF
}

declare -a args deps ignores wordlists
unset append docache help proxy resume simulate timeout tls verbose
color="true"
curl="curl -IkLs"
deps+=("curl")
deps+=("jq")
deps+=("parallel")
threads="32"

# Check for missing dependencies
check_deps

# Parse command line options
while [[ $# -gt 0 ]]; do
    case "$1" in
        "--") shift && args+=("$@") && break ;;
        "-a"|"--append") append="true" ;;
        "-c"|"--cache") docache="true" ;;
        "-h"|"--help") help="true" ;;
        "-i"|"--ignore"*) ignores+=("$(long_opt "$@")") || shift ;;
        "-l"|"--list"*) wordlists+=("$(long_opt "$@")") || shift ;;
        "--nocolor") unset color ;;
        "-p"|"--proxy"*) proxy="--proxy $(long_opt "$@")" || shift ;;
        "-r"|"--resume") resume="--resume" ;;
        "--simulate") simulate="true" ;;
        "-t"|"--threads"*) threads="$(long_opt "$@")" || shift ;;
        "--timeout"*) timeout="-m $(long_opt "$@")" || shift ;;
        "--tls") tls="true" ;;
        "-v"|"--verbose") verbose="true" ;;
        *) args+=("$1") ;;
    esac
    shift
done
[[ ${#args[@]} -eq 0 ]] || set -- "${args[@]}"

# Check for valid params
[[ -z $help ]] || usage 0
[[ $# -le 1 ]] || usage 1
[[ $# -eq 1 ]] || [[ -n $docache$simulate ]] || usage 1

# Cite if needed
if [[ ! -f "$HOME/.parallel/will-cite" ]]; then
    mkdir -p "$HOME/.parallel"
    parallel --citation
fi

# Save host
host="${1:-${simulate:+simulation}}"

# Cache variables
hash="$(echo -n "$host" | sha256sum | awk '{print $1}')"
cache="$HOME/.cache/${0##*/}/$hash"
joblog="$cache/joblog.txt"
json="$cache/${0##*/}.json"

# If defaults lists are not cached, find and cache
dcache="$HOME/.cache/${0##*/}/default_list.locations"
[[ -f "$dcache" ]] || docache="true"
[[ -z $docache ]] || cache_default_lists
[[ -n $host ]] || exit

# Ensure host is reachable
if [[ -z $simulate ]]; then
    ping -c 1 -W 1 "${host%%[:/]*}" &>/dev/null
    [[ $? -eq 0 ]] || errx 3 "Target is out of range"
fi

# Use default lists if none provided or append was specified
if [[ ${#wordlists[@]} -eq 0 ]] || [[ -n $append ]]; then
    while read -r wordlist; do
        wordlists+=("$wordlist")
    done <"$dcache"; unset wordlist
fi

# Ensure lists are provided and valid
[[ ${#wordlists[@]} -ne 0 ]] || errx 4 "No wordlists provided"
for wordlist in "${wordlists[@]}"; do
    [[ -f "$wordlist" ]] || errx 5 "$wordlist does not exist"
done; unset wordlist

# Lock to prevent parallel issues
check_lock

# Check for resume file
check_resume_file
hide_cursor

[[ -z $resume ]] || info "Resuming..."

# Display logo
logo >&2

info "MegaBuster is targeting $host"
info "Processing wordlists for ammo"

total="0"
while read -r count; do
    ((total += count))
done < <(grep -chPvs "^( *#.*)?$" "${wordlists[@]}"); unset count
[[ $total -gt 0 ]] || errx 2 "No ammo"

subinfo "$total shots to fire"

# Create sub-script
script="/tmp/${0##*/}.parallel"
cat >"$script" <<EOF
#!/usr/bin/env bash

### Helpers begin
set -o noglob
err() { echo -e "\r${color:+\e[31m}[!] \$*\e[0m\e[K"; }
errx() { echo -e "\r${color:+\e[31m}[!] \${*:2}\e[0m\e[K"; exit \$1; }
good() { echo -e "\r${color:+\e[32m}[+] \$*\e[0m\e[K"; }
info() { echo -e "\r${color:+\e[37m}[*] \$*\e[0m\e[K"; }
subinfo() { echo -e "\r${color:+\e[36m}[=] \$*\e[0m\e[K"; }
warn() { echo -e "\r${color:+\e[33m}[-] \$*\e[0m\e[K"; }
### Helpers end

check() {
  # Check GET and POST
  local data line type
  for type in GET POST; do
    case "\$type" in
      "POST") data="{}" ;;
      *) unset data ;;
    esac
    while read -r line; do
      case "\$line" in
        404) continue ;;
        ${ignores:+$(join_with "|" "${ignores[@]}")) continue ;;}
        5*) err "\$type /\$1 (\$line)" ;;
        4*) warn "\$type /\$1 (\$line)" ;;
        3*) subinfo "\$type /\$1 (\${line/http*:\/\/$host/})" ;;
        *) good "\$type /\$1 (\$line)" ;;
      esac
    done < <(
      $curl \${data:+-d \$data} $proxy $timeout -X \$type \\
      "http${tls:+s}://$host/\$1" | \\
      awk '/^(HTTP|Location)/ {print \$2}' | tr -d "\r" | \\
      sed -r "\\\$!N;s/\n/ /"
    ); unset line
  done; unset type
}

simulate() {
  local ret type
  case "\$((RANDOM % 2))" in
    0) type="GET" ;;
    *) type="POST" ;;
  esac
  case "\$((RANDOM % 6))" in
    0) ret="200" ;;
    1) ret="301" ;;
    2) ret="302" ;;
    3) ret="401" ;;
    4) ret="403" ;;
    *) ret="500" ;;
  esac
  case "\$((RANDOM % 64))" in
    8)
      case "\$ret" in
        404) return ;;
        ${ignores:+$(join_with "|" "${ignores[@]}")) return ;;}
        5*) err "\$type /\$1 (\$ret)" ;;
        4*) warn "\$type /\$1 (\$ret)" ;;
        3*) subinfo "\$type /\$1 (\$ret /some/other/path)" ;;
        *) good "\$type /\$1 (\$ret)" ;;
      esac
      ;;
  esac
}

# Ignore comments
comment_regex="^( *#.*)?$"
[[ ! "\$1" =~ \$comment_regex ]] || exit

# Remove leading slashes and trailing ^M
path="\${1#\${1%%[^/]*}}"
path="\${path%}"

# Fix any other ^M
path="\${path///\\\\\\\r}"

if [[ "x$simulate" != "x" ]]; then
  simulate "\$path"
else
  check "\$path"
fi
EOF
chmod 700 "$script"

cat "${wordlists[@]}" | parallel --bar --joblog ${resume:++}"$joblog" \
    --lb -P "$threads" -r $resume "$script" {}
[[ -n $verbose ]] || echo -en "\e[1A\e[K" >&2

clean
