#!/usr/bin/env bash
# A script to copy files to a remote host via bash commands.
# by Miles Whittaker <mjwhitta@gmail.com>
#
# --------------------------------------------------------------------
# The MIT License (MIT)
#
# Copyright (c) 2018 Miles Whittaker
#
# Permission is hereby granted, free of charge, to any person
# obtaining a copy of this software and associated documentation files
# (the "Software"), to deal in the Software without restriction,
# including without limitation the rights to use, copy, modify, merge,
# publish, distribute, sublicense, and/or sell copies of the Software,
# and to permit persons to whom the Software is furnished to do so,
# subject to the following conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
# BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
# ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
# --------------------------------------------------------------------

usage() {
    echo "Usage: ${0/*\//} [OPTIONS] <file>"
    echo
    echo "Generate bash commands to recreate a file on a remote host"
    echo
    echo "Options:"
    echo "    -h, --help    Display this help message"
    echo
    exit $1
}

declare -a args

while [[ $# -gt 0 ]]; do
    case "$1" in
        "--") shift && args+=("$@") && break ;;
        "-h"|"--help") usage 0 ;;
        *) args+=("$1") ;;
    esac
    shift
done
[[ -z ${args[@]} ]] || set -- "${args[@]}"

[[ $# -eq 1 ]] || usage 1
[[ -f $1 ]] || usage 2
[[ -n $(command -v xclip) ]] || [[ -n $(command -v xsel) ]] || usage 3

file="$1"
filename="$(basename $file)"
buffer="/tmp/paste_copy.buffer"

echo "echo -n > $filename" >$buffer
cat "$file" | sed "s|^\(.*\)$|echo '\1' >>$filename|g" >>$buffer
echo "md5sum $filename" >>$buffer

if [[ -n $(command -v xsel) ]]; then
    cat $buffer | xsel -i --clipboard
elif [[ -n $(command -v xclip) ]]; then
    cat $buffer | xclip -i -selection clipboard
else
    echo "Please install xclip or xsel!"
fi

md5sum "$file"
