#!/usr/bin/env bash
# A script for summarizing nmap results.
# by Miles Whittaker <mjwhitta@gmail.com>
#
# --------------------------------------------------------------------
# The MIT License (MIT)
#
# Copyright (c) 2018 Miles Whittaker
#
# Permission is hereby granted, free of charge, to any person
# obtaining a copy of this software and associated documentation files
# (the "Software"), to deal in the Software without restriction,
# including without limitation the rights to use, copy, modify, merge,
# publish, distribute, sublicense, and/or sell copies of the Software,
# and to permit persons to whom the Software is furnished to do so,
# subject to the following conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
# BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
# ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
# --------------------------------------------------------------------

err() { echo -e "${color:+\e[31m}[!] $@\e[0m"; }

errx() { echo -e "${color:+\e[31m}[!] ${@:2}\e[0m"; exit $1; }

good() { echo -e "${color:+\e[32m}[+] $@\e[0m"; }

info() { echo -e "${color:+\e[37m}[*] $@\e[0m"; }

long_opt() {
    local arg shift="0"
    case "$1" in
        "--"*"="*) arg="${1#*=}"; [[ -n $arg ]] || usage 1 ;;
        *) shift="1"; shift; [[ $# -gt 0 ]] || usage 1; arg="$1" ;;
    esac
    echo "$arg"
    return $shift
}

usage() {
    echo "Usage: ${0/*\//} [OPTIONS] [host1]... [hostN]"
    echo
    echo "Searches for *.nmap files and greps for open ports"
    echo
    echo "Options:"
    echo "    -h, --help    Display this help message"
    echo "    --nocolor     Disable colorized output"
    echo
    exit $1
}

warn() { echo -e "${color:+\e[33m}[-] $@\e[0m"; }

declare -a args
unset help
color="true"
hosts="."

# Parse command line options
while [[ $# -gt 0 ]]; do
    case "$1" in
        "--") shift && args+=("$@") && break ;;
        "-h"|"--help") help="true" ;;
        "--nocolor") unset color ;;
        *) args+=("$1") ;;
    esac
    shift
done
[[ -z ${args[@]} ]] || set -- "${args[@]}"

# Check for valid params and missing dependencies
[[ -z $help ]] || usage 0
[[ $# -eq 0 ]] || hosts="$@"

# Hosts with open ports
unset found oldhost
while read -r line; do
    match="${line/*:/}"
    newhost="${line/:*/}"
    found="true"

    if [[ $newhost != $oldhost ]]; then
        [[ -z $oldhost ]] || echo
        echo -e "${color:+\e[37m}# ${newhost/.\//}\e[0m"
    fi
    echo "$match"

    oldhost="$newhost"
done < <(
    LC_ALL=C find $hosts -type f -name "*.nmap" -exec \
    grep -EHIis "[0-9]+/.*open" {} + | sed -r "s#/[^/]+\.nmap##g" | \
    sort -k 1,1 -k 2,2n -t ":"
)

[[ -z $found ]] || echo

# Host with no open ports
unset found oldhost
while read -r line; do
    newhost="${line/:*/}"
    found="true"

    if [[ $newhost != $oldhost ]]; then
        [[ -z $oldhost ]] || echo
        echo -e "${color:+\e[37m}# ${newhost/.\//}\e[0m"
        echo "No open ports"
        echo
    fi

    oldhost="$newhost"
done < <(
    LC_ALL=C find $hosts -type f -name "*.nmap" -exec \
    grep -EHIiLs "[0-9]+/.*open" {} + | sed -r "s#/[^/]+\.nmap##g" | \
    sort -k 1,1 -k 2,2n -t ":"
)

[[ -z $found ]] || echo -en "\e[1A\e[K"
