#!/usr/bin/env bash

err() { echo -e "${color:+\e[31m}[!] $@\e[0m"; }

errx() { echo -e "${color:+\e[31m}[!] ${@:2}\e[0m"; exit $1; }

good() { echo -e "${color:+\e[32m}[+] $@\e[0m"; }

info() { echo -e "${color:+\e[37m}[*] $@\e[0m"; }

long_opt() {
    local arg shift="0"
    case "$1" in
        "--"*"="*) arg="${1#*=}"; [[ -n $arg ]] || usage 1 ;;
        *) shift="1"; shift; [[ $# -gt 0 ]] || usage 1; arg="$1" ;;
    esac
    echo "$arg"
    return $shift
}

subinfo() { echo -e "${color:+\e[36m}[=] $@\e[0m"; }

usage() {
    echo "Usage: ${0##*/} [OPTIONS] [passwd]"
    echo
    echo "Prompt for a password and check against results from"
    echo "https://api.pwnedpasswords.com"
    echo
    echo "Options:"
    echo "    -h, --help    Display this help message"
    echo "    --nocolor     Disable colorized output"
    echo
    exit $1
}

warn() { echo -e "${color:+\e[33m}[-] $@\e[0m"; }

# Check for missing dependencies
for dep in curl sha1sum; do
    [[ -n $(command -v $dep) ]] || errx 2 "$dep is not installed"
done; unset dep

declare -a args
unset help
color="true"

# Parse command line options
while [[ $# -gt 0 ]]; do
    case "$1" in
        "--") shift && args+=("$@") && break ;;
        "-h"|"--help") help="true" ;;
        "--nocolor") unset color ;;
        *) args+=("$1") ;;
    esac
    shift
done
[[ -z ${args[@]} ]] || set -- "${args[@]}"

# Check for valid params
[[ -z $help ]] || usage 0
[[ $# -le 1 ]] || usage 1

if [[ $# -eq 0 ]]; then
    # Read in password
    read -p "Enter password: " -s passwd; echo
else
    # Password was provided
    passwd="$1"
fi

# Get SHA1
sha="$(echo -n "$passwd" | sha1sum | awk '{print $1}')"

# Use API to search for our hash
res="$(
    curl -kLs "https://api.pwnedpasswords.com/range/${sha:0:5}" | \
    grep -E "${sha:5}"
)"

# Display result
if [[ -n $res ]]; then
    err "$res"
else
    good "Password not found"
fi
