#!/usr/bin/env bash

### Helpers begin
check_deps() {
    local missing
    for d in "${deps[@]}"; do
        if [[ -z $(command -v "$d") ]]; then
            # Force absolute path
            if [[ ! -e "/$d" ]]; then
                err "$d was not found"
                missing="true"
            fi
        fi
    done; unset d
    [[ -z $missing ]] || exit 128
}
err() { echo -e "${color:+\e[31m}[!] $*\e[0m"; }
errx() { err "${*:2}"; exit "$1"; }
good() { echo -e "${color:+\e[32m}[+] $*\e[0m"; }
info() { echo -e "${color:+\e[37m}[*] $*\e[0m"; }
long_opt() {
    local arg shift="0"
    case "$1" in
        "--"*"="*) arg="${1#*=}"; [[ -n $arg ]] || return 127 ;;
        *) shift="1"; shift; [[ $# -gt 0 ]] || return 127; arg="$1" ;;
    esac
    echo "$arg"
    return $shift
}
subinfo() { echo -e "${color:+\e[36m}[=] $*\e[0m"; }
warn() { echo -e "${color:+\e[33m}[-] $*\e[0m"; }
### Helpers end

usage() {
    cat <<EOF
Usage: ${0##*/} [OPTIONS]

DESCRIPTION
    Launch sqlmap.

OPTIONS
    -c, --clear    Clear cache and download the newest sqlmap
    -h             Display this help message
    --help         Pass-thru to sqlmap
    --no-color     Disable colorized output

EOF
    exit "$1"
}

declare -a args
unset clear help
color="true"

# Parse command line options
while [[ $# -gt 0 ]]; do
    case "$1" in
        "--") shift; args+=("$@"); break ;;
        "-c"|"--clear") clear="true" ;;
        "-h") help="true" ;;
        "--no-color") unset color ;;
        *) args+=("$1") ;;
    esac
    case "$?" in
        0) ;;
        1) shift ;;
        *) usage $? ;;
    esac
    shift
done
[[ ${#args[@]} -eq 0 ]] || set -- "${args[@]}"

# Help info
[[ -z $help ]] || usage 0

# Check for missing dependencies
declare -a deps
deps+=("git")
deps+=("python3")
check_deps

# TODO Check for valid params

cache="$HOME/.cache/sqlmap"
mkdir -p "$(dirname "$cache")"

# Clear cached sqlmap if requested
[[ -z $clear ]] || rm -rf "$cache"

# Get sqlmap if missing
if [[ ! -d "$cache" ]]; then
    git clone https://github.com/sqlmapproject/sqlmap.git "$cache" \
        || errx 1 "Failed to download sqlmap"
else
    git -C "$cache" pull -r >/dev/null || \
        errx 1 "Failed to update sqlmap"
fi

cd "$cache" || errx 1 "where did sqlmap go?"
./sqlmap.py "$@"
