#!/usr/bin/env bash

### Helpers begin
check_deps() {
    for d in "${deps[@]}"; do
        [[ -n $(command -v "$d") ]] || errx 128 "$d is not installed"
    done; unset d
}
err() { echo -e "${color:+\e[31m}[!] $*\e[0m"; }
errx() { err "${*:2}"; exit "$1"; }
good() { echo -e "${color:+\e[32m}[+] $*\e[0m"; }
info() { echo -e "${color:+\e[37m}[*] $*\e[0m"; }
long_opt() {
    local arg shift="0"
    case "$1" in
        "--"*"="*) arg="${1#*=}"; [[ -n $arg ]] || usage 127 ;;
        *) shift="1"; shift; [[ $# -gt 0 ]] || usage 127; arg="$1" ;;
    esac
    echo "$arg"
    return $shift
}
subinfo() { echo -e "${color:+\e[36m}[=] $*\e[0m"; }
warn() { echo -e "${color:+\e[33m}[-] $*\e[0m"; }
### Helpers end

usage() {
    cat <<EOF
Usage: ${0##*/} [OPTIONS]

Launch ysoserial.

Options:
    -c, --clear    Clear cache and download the newest ysoserial
    -h, --help     Display this help message
    --no-color     Disable colorized output

EOF
    exit "$1"
}

declare -a args deps
unset clear help
color="true"
deps+=("curl")
deps+=("java")

# Check for missing dependencies
check_deps

# Parse command line options
while [[ $# -gt 0 ]]; do
    case "$1" in
        "--") shift && args+=("$@") && break ;;
        "-c"|"--clear-cache") clear="true" ;;
        "-h"|"--help") help="true" ;;
        "--no-color") unset color ;;
        *) args+=("$1") ;;
    esac
    shift
done
[[ ${#args[@]} -eq 0 ]] || set -- "${args[@]}"

# Check for valid params
[[ -z $help ]] || usage 0

cache="$HOME/.cache/ysoserial"
mkdir -p "$cache"

# Clear cached ysoserial if requested
[[ -z $clear ]] || find "$cache" -name "*.jar" -exec rm -f {} +

# Get ysoserial if missing
yso="$(find "$cache" -name "ysoserial.jar")"
if [[ -z $yso ]]; then
    url="https://jitpack.io"
    path="/com/github/frohoff/ysoserial/master-SNAPSHOT/"
    path+="ysoserial-master-SNAPSHOT.jar"

    name="ysoserial.jar"
    curl -Lo "$cache/$name" "$url/$path"
    [[ $? -eq 0 ]] || errx 1 "Failed to download ysoserial jar"

    yso="$(find "$cache" -name "ysoserial.jar")"
fi

java -jar "$yso" "$@"
