#!/usr/bin/env bash
# A script to prevent runaway processes.
# by Miles Whittaker <mjwhitta@gmail.com>
#
# --------------------------------------------------------------------
# The MIT License (MIT)
#
# Copyright (c) 2018 Miles Whittaker
#
# Permission is hereby granted, free of charge, to any person
# obtaining a copy of this software and associated documentation files
# (the "Software"), to deal in the Software without restriction,
# including without limitation the rights to use, copy, modify, merge,
# publish, distribute, sublicense, and/or sell copies of the Software,
# and to permit persons to whom the Software is furnished to do so,
# subject to the following conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
# BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
# ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
# --------------------------------------------------------------------

err() { echo -e "${color:+\e[31m}[!] $@\e[0m"; }

errx() { echo -e "${color:+\e[31m}[!] ${@:2}\e[0m"; exit $1; }

good() { echo -e "${color:+\e[32m}[+] $@\e[0m"; }

info() { echo -e "${color:+\e[37m}[*] $@\e[0m"; }

long_opt() {
    local arg shift="0"
    case "$1" in
        "--"*"="*) arg="${1#*=}"; [[ -n $arg ]] || usage 1 ;;
        *) shift="1"; shift; [[ $# -gt 0 ]] || usage 1; arg="$1" ;;
    esac
    echo "$arg"
    return $shift
}

usage() {
    echo "Usage: ${0/*\//} [OPTIONS]"
    echo
    echo "Prevent processes from rapidly spawning (sometimes happens"
    echo "with xdg-open)"
    echo
    echo "Options:"
    echo "    -c, --count        Show count of each running command"
    echo "    -h, --help         Display this help message"
    echo "    -m, --max=MAX      Set maximum allowed process count"
    echo "                       (default: $max)"
    echo "    --nocolor          Disable colorized output"
    echo "    -p, --proc=PROC    Only check processes matching PROC"
    echo
    exit $1
}

warn() { echo -e "${color:+\e[33m}[-] $@\e[0m"; }

declare -a args
unset help proc show_count
color="true"
max="64"

# Parse command line options
while [[ $# -gt 0 ]]; do
    case "$1" in
        "--") shift && args+=("$@") && break ;;
        "-c"|"--count") show_count="true" ;;
        "-h"|"--help") help="true" ;;
        "-m"|"--max"*) max="$(long_opt "$@")" || shift ;;
        "--nocolor") unset color ;;
        "-p"|"--proc"*) proc="$(long_opt "$@")" || shift ;;
        *) args+=("$1") ;;
    esac
    shift
done
[[ -z ${args[@]} ]] || set -- "${args[@]}"

# Check for valid params and missing dependencies
[[ -z $help ]] || usage 0
[[ $# -eq 0 ]] || usage 2

while read c p; do
    if [[ -n $show_count ]]; then
        if [[ -n $proc ]]; then
            case "$p" in
                *"$proc"*) ;;
                *) continue ;;
            esac
        fi
        if [[ $c -ge $max ]]; then
            warn "$c $p"
        else
            good "$c $p"
        fi
    elif [[ -n $proc ]]; then
        [[ "$p" == "$proc" ]] && [[ $c -ge $max ]] && killall $p
    else
        [[ $c -ge $max ]] && killall $p
    fi
done < <(ps -e -o comm | tail -n +2 | sort | uniq -c | sort -n -r)
