#!/usr/bin/env bash
# A script to prevent runaway processes.
# by Miles Whittaker <mj@whitta.dev>
#
# --------------------------------------------------------------------
# The MIT License (MIT)
#
# Copyright (c) 2020 Miles Whittaker
#
# Permission is hereby granted, free of charge, to any person
# obtaining a copy of this software and associated documentation files
# (the "Software"), to deal in the Software without restriction,
# including without limitation the rights to use, copy, modify, merge,
# publish, distribute, sublicense, and/or sell copies of the Software,
# and to permit persons to whom the Software is furnished to do so,
# subject to the following conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
# BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
# ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
# --------------------------------------------------------------------

### Helpers begin
check_deps() {
    for d in "${deps[@]}"; do
        [[ -n $(command -v "$d") ]] || errx 128 "$d is not installed"
    done; unset d
}
err() { echo -e "${color:+\e[31m}[!] $*\e[0m"; }
errx() { err "${*:2}"; exit "$1"; }
good() { echo -e "${color:+\e[32m}[+] $*\e[0m"; }
info() { echo -e "${color:+\e[37m}[*] $*\e[0m"; }
long_opt() {
    local arg shift="0"
    case "$1" in
        "--"*"="*) arg="${1#*=}"; [[ -n $arg ]] || usage 127 ;;
        *) shift="1"; shift; [[ $# -gt 0 ]] || usage 127; arg="$1" ;;
    esac
    echo "$arg"
    return $shift
}
subinfo() { echo -e "${color:+\e[36m}[=] $*\e[0m"; }
warn() { echo -e "${color:+\e[33m}[-] $*\e[0m"; }
### Helpers end

usage() {
    cat <<EOF
Usage: ${0##*/} [OPTIONS]

Prevent processes from rapidly spawning (sometimes happens with
xdg-open).

Options:
    -c, --count        Show count of each running command
    -h, --help         Display this help message
    -m, --max=MAX      Set maximum allowed process count (default: 64)
    --nocolor          Disable colorized output
    -p, --proc=PROC    Only check processes matching PROC

EOF
    exit "$1"
}

declare -a args deps
unset help proc show_count
color="true"
# deps+=("todo")
max="64"

# Check for missing dependencies
check_deps

# Parse command line options
while [[ $# -gt 0 ]]; do
    case "$1" in
        "--") shift && args+=("$@") && break ;;
        "-c"|"--count") show_count="true" ;;
        "-h"|"--help") help="true" ;;
        "-m"|"--max"*) max="$(long_opt "$@")" || shift ;;
        "--nocolor") unset color ;;
        "-p"|"--proc"*) proc="$(long_opt "$@")" || shift ;;
        *) args+=("$1") ;;
    esac
    shift
done
[[ ${#args[@]} -eq 0 ]] || set -- "${args[@]}"

# Check for valid params
[[ -z $help ]] || usage 0
[[ $# -eq 0 ]] || usage 1

while read -r c p; do
    if [[ -n $show_count ]]; then
        if [[ -n $proc ]]; then
            case "$p" in
                *"$proc"*) ;;
                *) continue ;;
            esac
        fi
        if [[ $c -ge $max ]]; then
            warn "$c $p"
        else
            good "$c $p"
        fi
    elif [[ -n $proc ]]; then
        [[ "$p" == "$proc" ]] && [[ $c -ge $max ]] && killall "$p"
    else
        [[ $c -ge $max ]] && killall "$p"
    fi
done < <(ps -e -o comm | tail -n +2 | sort | uniq -c | sort -n -r)
unset c p
