#!/usr/bin/env bash

err() { echo -e "${color:+\e[31m}[!] $@\e[0m"; }

errx() { echo -e "${color:+\e[31m}[!] ${@:2}\e[0m"; exit $1; }

good() { echo -e "${color:+\e[32m}[+] $@\e[0m"; }

info() { echo -e "${color:+\e[37m}[*] $@\e[0m"; }

long_opt() {
    local arg shift="0"
    case "$1" in
        "--"*"="*) arg="${1#*=}"; [[ -n $arg ]] || usage 1 ;;
        *) shift="1"; shift; [[ $# -gt 0 ]] || usage 1; arg="$1" ;;
    esac
    echo "$arg"
    return $shift
}

usage() {
    echo "Usage: ${0/*\//} [OPTIONS]"
    echo
    echo "Use xdotool to fix any special keys that are sticking"
    echo
    echo "Options:"
    echo "    -h, --help    Display this help message"
    echo "    --nocolor     Disable colorized output"
    echo
    exit $1
}

warn() { echo -e "${color:+\e[33m}[-] $@\e[0m"; }

declare -a args
unset help
color="true"

# Parse command line options
while [[ $# -gt 0 ]]; do
    case "$1" in
        "--") shift && args+=("$@") && break ;;
        "-h"|"--help") help="true" ;;
        "--nocolor") unset color ;;
        *) args+=("$1") ;;
    esac
    shift
done
[[ -z ${args[@]} ]] || set -- "${args[@]}"

# Check for valid params and missing dependencies
[[ -z $help ]] || usage 0
[[ $# -eq 0 ]] || usage 1
for dep in perl xdotool; do
    [[ -n $(command -v $dep) ]] || errx 2 "$dep is not installed"
done; unset dep

unset keys
if [[ -f /usr/include/X11/keysymdef.h ]]; then
    keys="$(
        perl -lne '/#define\s+XK_(\S+_(L|R|Level.*))\s/ && print $1' \
        /usr/include/X11/keysymdef.h
    )"
fi
[[ -z $keys ]] || xdotool keyup $keys
